/*
 * Created on 29 Sep 2017 ( Time 15:10:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package au.com.jaycar.local.entity.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "polines"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="polines", catalog="coreinfo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PolinesEntity.countAll", query="SELECT COUNT(x) FROM PolinesEntity x" ),
  @NamedQuery ( name="PolinesEntity.findByCode", query="SELECT x FROM PolinesEntity x WHERE x.code = :code" )
} )
public class PolinesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="PK", nullable=false)
    private Integer    pk           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="code", length=10)
    private String     code         ;

    @Temporal(TemporalType.DATE)
    @Column(name="poit_duedate")
    private Date       poitDuedate  ;

    @Column(name="poit_qtyord", length=45)
    private String     poitQtyord   ;

    @Column(name="pord_order", length=45)
    private String     pordOrder    ;

    @Column(name="warehouse", length=45)
    private String     warehouse    ;

    @Column(name="polinescol", length=45)
    private String     polinescol   ;

    @Column(name="freeqty", length=45)
    private String     freeqty      ;

    @Column(name="outqty", length=45)
    private String     outqty       ;

    @Column(name="poit_line", length=45)
    private String     poitLine     ;

    @Column(name="poit_ackref", length=45)
    private String     poitAckref   ;

    @Temporal(TemporalType.DATE)
    @Column(name="reqdate")
    private Date       reqdate      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PolinesEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPk( Integer pk ) {
        this.pk = pk ;
    }
    public Integer getPk() {
        return this.pk;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : code ( VARCHAR ) 
    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }

    //--- DATABASE MAPPING : poit_duedate ( DATE ) 
    public void setPoitDuedate( Date poitDuedate ) {
        this.poitDuedate = poitDuedate;
    }
    public Date getPoitDuedate() {
        return this.poitDuedate;
    }

    //--- DATABASE MAPPING : poit_qtyord ( VARCHAR ) 
    public void setPoitQtyord( String poitQtyord ) {
        this.poitQtyord = poitQtyord;
    }
    public String getPoitQtyord() {
        return this.poitQtyord;
    }

    //--- DATABASE MAPPING : pord_order ( VARCHAR ) 
    public void setPordOrder( String pordOrder ) {
        this.pordOrder = pordOrder;
    }
    public String getPordOrder() {
        return this.pordOrder;
    }

    //--- DATABASE MAPPING : warehouse ( VARCHAR ) 
    public void setWarehouse( String warehouse ) {
        this.warehouse = warehouse;
    }
    public String getWarehouse() {
        return this.warehouse;
    }

    //--- DATABASE MAPPING : polinescol ( VARCHAR ) 
    public void setPolinescol( String polinescol ) {
        this.polinescol = polinescol;
    }
    public String getPolinescol() {
        return this.polinescol;
    }

    //--- DATABASE MAPPING : freeqty ( VARCHAR ) 
    public void setFreeqty( String freeqty ) {
        this.freeqty = freeqty;
    }
    public String getFreeqty() {
        return this.freeqty;
    }

    //--- DATABASE MAPPING : outqty ( VARCHAR ) 
    public void setOutqty( String outqty ) {
        this.outqty = outqty;
    }
    public String getOutqty() {
        return this.outqty;
    }

    //--- DATABASE MAPPING : poit_line ( VARCHAR ) 
    public void setPoitLine( String poitLine ) {
        this.poitLine = poitLine;
    }
    public String getPoitLine() {
        return this.poitLine;
    }

    //--- DATABASE MAPPING : poit_ackref ( VARCHAR ) 
    public void setPoitAckref( String poitAckref ) {
        this.poitAckref = poitAckref;
    }
    public String getPoitAckref() {
        return this.poitAckref;
    }

    //--- DATABASE MAPPING : reqdate ( DATE ) 
    public void setReqdate( Date reqdate ) {
        this.reqdate = reqdate;
    }
    public Date getReqdate() {
        return this.reqdate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(pk);
        sb.append("]:"); 
        sb.append(code);
        sb.append("|");
        sb.append(poitDuedate);
        sb.append("|");
        sb.append(poitQtyord);
        sb.append("|");
        sb.append(pordOrder);
        sb.append("|");
        sb.append(warehouse);
        sb.append("|");
        sb.append(polinescol);
        sb.append("|");
        sb.append(freeqty);
        sb.append("|");
        sb.append(outqty);
        sb.append("|");
        sb.append(poitLine);
        sb.append("|");
        sb.append(poitAckref);
        sb.append("|");
        sb.append(reqdate);
        return sb.toString(); 
    } 

}
