package au.com.jaycar.warehouse.mapping;

import au.com.jaycar.warehouse.entity.Cmprod;
import au.com.jaycar.warehouse.entity.CmprodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmprodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.CMPROD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    long countByExample(CmprodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.CMPROD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int deleteByExample(CmprodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.CMPROD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int insert(Cmprod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.CMPROD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int insertSelective(Cmprod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.CMPROD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    List<Cmprod> selectByExample(CmprodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.CMPROD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int updateByExampleSelective(@Param("record") Cmprod record, @Param("example") CmprodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.CMPROD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int updateByExample(@Param("record") Cmprod record, @Param("example") CmprodExample example);
}