package au.com.jaycar.warehouse.mapping;

import au.com.jaycar.warehouse.entity.Sohead;
import au.com.jaycar.warehouse.entity.SoheadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SoheadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    long countByExample(SoheadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int deleteByExample(SoheadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int insert(Sohead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int insertSelective(Sohead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    List<Sohead> selectByExample(SoheadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int updateByExampleSelective(@Param("record") Sohead record, @Param("example") SoheadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int updateByExample(@Param("record") Sohead record, @Param("example") SoheadExample example);
}