package au.com.jaycar.warehouse.mapping;

import au.com.jaycar.warehouse.entity.Soitem;
import au.com.jaycar.warehouse.entity.SoitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SoitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOITEM
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    long countByExample(SoitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOITEM
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int deleteByExample(SoitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOITEM
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int insert(Soitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOITEM
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int insertSelective(Soitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOITEM
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    List<Soitem> selectByExample(SoitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOITEM
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int updateByExampleSelective(@Param("record") Soitem record, @Param("example") SoitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.SOITEM
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int updateByExample(@Param("record") Soitem record, @Param("example") SoitemExample example);
}