package au.com.jaycar.warehouse.mapping;

import au.com.jaycar.warehouse.entity.Stock;
import au.com.jaycar.warehouse.entity.StockExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.STOCK
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    long countByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.STOCK
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int deleteByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.STOCK
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int insert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.STOCK
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int insertSelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.STOCK
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    List<Stock> selectByExample(StockExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.STOCK
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int updateByExampleSelective(@Param("record") Stock record, @Param("example") StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.STOCK
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int updateByExample(@Param("record") Stock record, @Param("example") StockExample example);
}