package au.com.jaycar.warehouse.mapping;

import au.com.jaycar.warehouse.entity.Wohead;
import au.com.jaycar.warehouse.entity.WoheadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WoheadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.WOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    long countByExample(WoheadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.WOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int deleteByExample(WoheadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.WOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int insert(Wohead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.WOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int insertSelective(Wohead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.WOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    List<Wohead> selectByExample(WoheadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.WOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int updateByExampleSelective(@Param("record") Wohead record, @Param("example") WoheadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MDST.WOHEAD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    int updateByExample(@Param("record") Wohead record, @Param("example") WoheadExample example);
}