package au.com.jaycar.mdm.mapping;

import au.com.jaycar.mdm.entity.Medias;
import au.com.jaycar.mdm.entity.MediasExample;
import au.com.jaycar.mdm.entity.MediasWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MediasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    long countByExample(MediasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    int deleteByExample(MediasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    int deleteByPrimaryKey(Long pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    int insert(MediasWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    int insertSelective(MediasWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    List<MediasWithBLOBs> selectByExampleWithBLOBs(MediasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    List<Medias> selectByExample(MediasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    MediasWithBLOBs selectByPrimaryKey(Long pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    int updateByExampleSelective(@Param("record") MediasWithBLOBs record, @Param("example") MediasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    int updateByExampleWithBLOBs(@Param("record") MediasWithBLOBs record, @Param("example") MediasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    int updateByExample(@Param("record") Medias record, @Param("example") MediasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    int updateByPrimaryKeySelective(MediasWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    int updateByPrimaryKeyWithBLOBs(MediasWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medias
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    int updateByPrimaryKey(Medias record);
}