package au.com.jaycar.mdm.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import au.com.jaycar.mdm.entity.Products;
import au.com.jaycar.mdm.entity.ProductsExample;
import au.com.jaycar.mdm.entity.ProductsWithBLOBs;

public interface ProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    long countByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int deleteByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int deleteByPrimaryKey(Long pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int insert(ProductsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int insertSelective(ProductsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    List<ProductsWithBLOBs> selectByExampleWithBLOBs(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    List<Products> selectByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    ProductsWithBLOBs selectByPrimaryKey(Long pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByExampleSelective(@Param("record") ProductsWithBLOBs record, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ProductsWithBLOBs record, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByExample(@Param("record") Products record, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByPrimaryKeySelective(ProductsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByPrimaryKeyWithBLOBs(ProductsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByPrimaryKey(Products record);
}