package au.com.jaycar.mdm.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import au.com.jaycar.mdm.entity.Productfeatures;
import au.com.jaycar.mdm.entity.ProductfeaturesExample;
import au.com.jaycar.mdm.entity.ProductfeaturesWithBLOBs;

public interface ProductfeaturesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    long countByExample(ProductfeaturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int deleteByExample(ProductfeaturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int deleteByPrimaryKey(Long pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int insert(ProductfeaturesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int insertSelective(ProductfeaturesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    List<ProductfeaturesWithBLOBs> selectByExampleWithBLOBs(ProductfeaturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    List<Productfeatures> selectByExample(ProductfeaturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    ProductfeaturesWithBLOBs selectByPrimaryKey(Long pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByExampleSelective(@Param("record") ProductfeaturesWithBLOBs record, @Param("example") ProductfeaturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ProductfeaturesWithBLOBs record, @Param("example") ProductfeaturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByExample(@Param("record") Productfeatures record, @Param("example") ProductfeaturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByPrimaryKeySelective(ProductfeaturesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByPrimaryKeyWithBLOBs(ProductfeaturesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productfeatures
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    int updateByPrimaryKey(Productfeatures record);
}