
/*
 * Created on 29 Sep 2017 ( Time 15:10:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package au.com.jaycar.local.mock;

import java.util.LinkedList;
import java.util.List;

import au.com.jaycar.local.entity.jpa.ProductsEntity;
import au.com.jaycar.local.mock.tool.MockValues;

public class ProductsEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ProductsEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ProductsEntity createInstance( Integer pk ) {
		ProductsEntity entity = new ProductsEntity();
		// Init Primary Key fields
		entity.setPk( pk) ;
		// Init Data fields
		entity.setCode( mockValues.nextString(10) ) ; // java.lang.String 
		entity.setRtmcode( mockValues.nextString(10) ) ; // java.lang.String 
		entity.setPProddescmarket( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setPProddescsystem( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setPCopyretail( mockValues.nextString(65535) ) ; // java.lang.String 
		entity.setPCopyweb( mockValues.nextString(65535) ) ; // java.lang.String 
		entity.setPCopywholesale( mockValues.nextString(65535) ) ; // java.lang.String 
		entity.setJaycarpagenum( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setJaycaryear( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setRtmpagenum( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setRtmyear( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setPProdstatus( mockValues.nextString(3) ) ; // java.lang.String 
		entity.setPProdwarrext( mockValues.nextString(5) ) ; // java.lang.String 
		entity.setPProdwarrexclusion( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setLeadtime( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setBoxqty( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgmain( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgfront( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgrear( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImglside( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgrside( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgtop( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImginsit( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgacc( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgpkd( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgclose( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImginuse( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgopen( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgclosed( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImglinediagram( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPImgfeatures( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPManualmain( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPDatasheetmain( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPFirmwaremain( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPDrivermain( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPSoftwaremain( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPMsdsmain( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setCreatetime( mockValues.nextDate() ) ; // java.util.Date 
		entity.setModifiedtime( mockValues.nextDate() ) ; // java.util.Date 
		entity.setPProdbrand( mockValues.nextString(65) ) ; // java.lang.String 
		entity.setPProdtagline( mockValues.nextString(255) ) ; // java.lang.String 
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ProductsEntity> createList(int count) {
		List<ProductsEntity> list = new LinkedList<ProductsEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
