
/*
 * Created on 29 Sep 2017 ( Time 15:10:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package au.com.jaycar.local.mock;

import java.util.LinkedList;
import java.util.List;

import au.com.jaycar.local.entity.jpa.StockEntity;
import au.com.jaycar.local.mock.tool.MockValues;

public class StockEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public StockEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public StockEntity createInstance( Integer pk ) {
		StockEntity entity = new StockEntity();
		// Init Primary Key fields
		entity.setPk( pk) ;
		// Init Data fields
		entity.setCode( mockValues.nextString(10) ) ; // java.lang.String 
		entity.setStkLoc( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setStkStkqty( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setStkAllstk( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setStocklevel( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setStkTotord( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<StockEntity> createList(int count) {
		List<StockEntity> list = new LinkedList<StockEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
