package au.com.jaycar.warehouse.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Porder {
	
 
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SUPPLIER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSupplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_BRANCH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ORDER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_TYPE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_DATEORD
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Date pordDateord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_USERID
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_NODEL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordNodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_AUTHOR
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_PONDTYPE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordPondtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_PONDCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordPondcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ORDVALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal pordOrdvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_DELVALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal pordDelvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_INVVALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal pordInvvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_OUTITEMS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Long pordOutitems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_DELQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal pordDelqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_INVQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal pordInvqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_LASTDEL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Date pordLastdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_TERMS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordTerms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_COSTMETH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordCostmeth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_COSTCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordCostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_WT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordWt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SUBCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSubcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_DELDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Date pordDeldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_TERNAL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordTernal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_PSTATUS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordPstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_REVNUM
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Integer pordRevnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_APSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordApstat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_CASH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordCash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ACKREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordAckref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ACKDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Date pordAckdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ORIGIN
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ORIGREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordOrigref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_CVRATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal pordCvrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_DIV
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordDiv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_EXPFORM
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordExpform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_LETTCRED
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordLettcred;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SECURITY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSecurity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_REF1
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordRef1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_REF2
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordRef2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_DELTERM
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordDelterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SPECDEAL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSpecdeal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_CUSTOMER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordCustomer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SUPPREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSuppref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_COMPANY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SUPNDCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSupndcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_DIRLOC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordDirloc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ESN
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Long pordEsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ESSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Integer pordEsseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_CCOMP
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordCcomp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SHIPMETH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordShipmeth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_CURRENCY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_PRCOPIES
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Long pordPrcopies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_REPREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordRepref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ACKSTATUS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordAckstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_PIGRP
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordPigrp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_FPREG
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordFpreg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SUPPSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSuppstat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_LASTAMEND
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Date pordLastamend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_CALL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordCall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_IRREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordIrref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SUBPOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSubpost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_NOINV
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordNoinv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_CALLALNK
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordCallalnk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_MEFFDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Date pordMeffdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_MEXPDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Date pordMexpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SUPMREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSupmref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SUPMDESC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSupmdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ULOC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordUloc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_FAX
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_EMAIL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_ORDTYPE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordOrdtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_POROUTE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordPoroute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_CONTACT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_CONREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordConref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_POLIMIT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordPolimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_SENT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordSent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.PORDER.PORD_CAREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String pordCaref;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SUPPLIER
     *
     * @return the value of MDST.PORDER.PORD_SUPPLIER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSupplier() {
        return pordSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SUPPLIER
     *
     * @param pordSupplier the value for MDST.PORDER.PORD_SUPPLIER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSupplier(String pordSupplier) {
        this.pordSupplier = pordSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_BRANCH
     *
     * @return the value of MDST.PORDER.PORD_BRANCH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordBranch() {
        return pordBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_BRANCH
     *
     * @param pordBranch the value for MDST.PORDER.PORD_BRANCH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordBranch(String pordBranch) {
        this.pordBranch = pordBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ORDER
     *
     * @return the value of MDST.PORDER.PORD_ORDER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordOrder() {
        return pordOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ORDER
     *
     * @param pordOrder the value for MDST.PORDER.PORD_ORDER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordOrder(String pordOrder) {
        this.pordOrder = pordOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_TYPE
     *
     * @return the value of MDST.PORDER.PORD_TYPE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordType() {
        return pordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_TYPE
     *
     * @param pordType the value for MDST.PORDER.PORD_TYPE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordType(String pordType) {
        this.pordType = pordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_DATEORD
     *
     * @return the value of MDST.PORDER.PORD_DATEORD
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Date getPordDateord() {
        return pordDateord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_DATEORD
     *
     * @param pordDateord the value for MDST.PORDER.PORD_DATEORD
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordDateord(Date pordDateord) {
        this.pordDateord = pordDateord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_USERID
     *
     * @return the value of MDST.PORDER.PORD_USERID
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordUserid() {
        return pordUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_USERID
     *
     * @param pordUserid the value for MDST.PORDER.PORD_USERID
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordUserid(String pordUserid) {
        this.pordUserid = pordUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_NODEL
     *
     * @return the value of MDST.PORDER.PORD_NODEL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordNodel() {
        return pordNodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_NODEL
     *
     * @param pordNodel the value for MDST.PORDER.PORD_NODEL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordNodel(String pordNodel) {
        this.pordNodel = pordNodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_AUTHOR
     *
     * @return the value of MDST.PORDER.PORD_AUTHOR
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordAuthor() {
        return pordAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_AUTHOR
     *
     * @param pordAuthor the value for MDST.PORDER.PORD_AUTHOR
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordAuthor(String pordAuthor) {
        this.pordAuthor = pordAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_PONDTYPE
     *
     * @return the value of MDST.PORDER.PORD_PONDTYPE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordPondtype() {
        return pordPondtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_PONDTYPE
     *
     * @param pordPondtype the value for MDST.PORDER.PORD_PONDTYPE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordPondtype(String pordPondtype) {
        this.pordPondtype = pordPondtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_PONDCODE
     *
     * @return the value of MDST.PORDER.PORD_PONDCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordPondcode() {
        return pordPondcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_PONDCODE
     *
     * @param pordPondcode the value for MDST.PORDER.PORD_PONDCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordPondcode(String pordPondcode) {
        this.pordPondcode = pordPondcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ORDVALUE
     *
     * @return the value of MDST.PORDER.PORD_ORDVALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getPordOrdvalue() {
        return pordOrdvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ORDVALUE
     *
     * @param pordOrdvalue the value for MDST.PORDER.PORD_ORDVALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordOrdvalue(BigDecimal pordOrdvalue) {
        this.pordOrdvalue = pordOrdvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_DELVALUE
     *
     * @return the value of MDST.PORDER.PORD_DELVALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getPordDelvalue() {
        return pordDelvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_DELVALUE
     *
     * @param pordDelvalue the value for MDST.PORDER.PORD_DELVALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordDelvalue(BigDecimal pordDelvalue) {
        this.pordDelvalue = pordDelvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_INVVALUE
     *
     * @return the value of MDST.PORDER.PORD_INVVALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getPordInvvalue() {
        return pordInvvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_INVVALUE
     *
     * @param pordInvvalue the value for MDST.PORDER.PORD_INVVALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordInvvalue(BigDecimal pordInvvalue) {
        this.pordInvvalue = pordInvvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_OUTITEMS
     *
     * @return the value of MDST.PORDER.PORD_OUTITEMS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Long getPordOutitems() {
        return pordOutitems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_OUTITEMS
     *
     * @param pordOutitems the value for MDST.PORDER.PORD_OUTITEMS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordOutitems(Long pordOutitems) {
        this.pordOutitems = pordOutitems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_DELQTY
     *
     * @return the value of MDST.PORDER.PORD_DELQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getPordDelqty() {
        return pordDelqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_DELQTY
     *
     * @param pordDelqty the value for MDST.PORDER.PORD_DELQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordDelqty(BigDecimal pordDelqty) {
        this.pordDelqty = pordDelqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_INVQTY
     *
     * @return the value of MDST.PORDER.PORD_INVQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getPordInvqty() {
        return pordInvqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_INVQTY
     *
     * @param pordInvqty the value for MDST.PORDER.PORD_INVQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordInvqty(BigDecimal pordInvqty) {
        this.pordInvqty = pordInvqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_LASTDEL
     *
     * @return the value of MDST.PORDER.PORD_LASTDEL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Date getPordLastdel() {
        return pordLastdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_LASTDEL
     *
     * @param pordLastdel the value for MDST.PORDER.PORD_LASTDEL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordLastdel(Date pordLastdel) {
        this.pordLastdel = pordLastdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_TERMS
     *
     * @return the value of MDST.PORDER.PORD_TERMS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordTerms() {
        return pordTerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_TERMS
     *
     * @param pordTerms the value for MDST.PORDER.PORD_TERMS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordTerms(String pordTerms) {
        this.pordTerms = pordTerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_COSTMETH
     *
     * @return the value of MDST.PORDER.PORD_COSTMETH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordCostmeth() {
        return pordCostmeth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_COSTMETH
     *
     * @param pordCostmeth the value for MDST.PORDER.PORD_COSTMETH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCostmeth(String pordCostmeth) {
        this.pordCostmeth = pordCostmeth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_COSTCODE
     *
     * @return the value of MDST.PORDER.PORD_COSTCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordCostcode() {
        return pordCostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_COSTCODE
     *
     * @param pordCostcode the value for MDST.PORDER.PORD_COSTCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCostcode(String pordCostcode) {
        this.pordCostcode = pordCostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_WT
     *
     * @return the value of MDST.PORDER.PORD_WT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordWt() {
        return pordWt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_WT
     *
     * @param pordWt the value for MDST.PORDER.PORD_WT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordWt(String pordWt) {
        this.pordWt = pordWt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SUBCODE
     *
     * @return the value of MDST.PORDER.PORD_SUBCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSubcode() {
        return pordSubcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SUBCODE
     *
     * @param pordSubcode the value for MDST.PORDER.PORD_SUBCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSubcode(String pordSubcode) {
        this.pordSubcode = pordSubcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_DELDATE
     *
     * @return the value of MDST.PORDER.PORD_DELDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Date getPordDeldate() {
        return pordDeldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_DELDATE
     *
     * @param pordDeldate the value for MDST.PORDER.PORD_DELDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordDeldate(Date pordDeldate) {
        this.pordDeldate = pordDeldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_TERNAL
     *
     * @return the value of MDST.PORDER.PORD_TERNAL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordTernal() {
        return pordTernal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_TERNAL
     *
     * @param pordTernal the value for MDST.PORDER.PORD_TERNAL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordTernal(String pordTernal) {
        this.pordTernal = pordTernal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_PSTATUS
     *
     * @return the value of MDST.PORDER.PORD_PSTATUS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordPstatus() {
        return pordPstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_PSTATUS
     *
     * @param pordPstatus the value for MDST.PORDER.PORD_PSTATUS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordPstatus(String pordPstatus) {
        this.pordPstatus = pordPstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_REVNUM
     *
     * @return the value of MDST.PORDER.PORD_REVNUM
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Integer getPordRevnum() {
        return pordRevnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_REVNUM
     *
     * @param pordRevnum the value for MDST.PORDER.PORD_REVNUM
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordRevnum(Integer pordRevnum) {
        this.pordRevnum = pordRevnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_APSTAT
     *
     * @return the value of MDST.PORDER.PORD_APSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordApstat() {
        return pordApstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_APSTAT
     *
     * @param pordApstat the value for MDST.PORDER.PORD_APSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordApstat(String pordApstat) {
        this.pordApstat = pordApstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_CASH
     *
     * @return the value of MDST.PORDER.PORD_CASH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordCash() {
        return pordCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_CASH
     *
     * @param pordCash the value for MDST.PORDER.PORD_CASH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCash(String pordCash) {
        this.pordCash = pordCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ACKREF
     *
     * @return the value of MDST.PORDER.PORD_ACKREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordAckref() {
        return pordAckref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ACKREF
     *
     * @param pordAckref the value for MDST.PORDER.PORD_ACKREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordAckref(String pordAckref) {
        this.pordAckref = pordAckref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ACKDATE
     *
     * @return the value of MDST.PORDER.PORD_ACKDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Date getPordAckdate() {
        return pordAckdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ACKDATE
     *
     * @param pordAckdate the value for MDST.PORDER.PORD_ACKDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordAckdate(Date pordAckdate) {
        this.pordAckdate = pordAckdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ORIGIN
     *
     * @return the value of MDST.PORDER.PORD_ORIGIN
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordOrigin() {
        return pordOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ORIGIN
     *
     * @param pordOrigin the value for MDST.PORDER.PORD_ORIGIN
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordOrigin(String pordOrigin) {
        this.pordOrigin = pordOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ORIGREF
     *
     * @return the value of MDST.PORDER.PORD_ORIGREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordOrigref() {
        return pordOrigref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ORIGREF
     *
     * @param pordOrigref the value for MDST.PORDER.PORD_ORIGREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordOrigref(String pordOrigref) {
        this.pordOrigref = pordOrigref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_CVRATE
     *
     * @return the value of MDST.PORDER.PORD_CVRATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getPordCvrate() {
        return pordCvrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_CVRATE
     *
     * @param pordCvrate the value for MDST.PORDER.PORD_CVRATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCvrate(BigDecimal pordCvrate) {
        this.pordCvrate = pordCvrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_DIV
     *
     * @return the value of MDST.PORDER.PORD_DIV
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordDiv() {
        return pordDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_DIV
     *
     * @param pordDiv the value for MDST.PORDER.PORD_DIV
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordDiv(String pordDiv) {
        this.pordDiv = pordDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_EXPFORM
     *
     * @return the value of MDST.PORDER.PORD_EXPFORM
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordExpform() {
        return pordExpform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_EXPFORM
     *
     * @param pordExpform the value for MDST.PORDER.PORD_EXPFORM
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordExpform(String pordExpform) {
        this.pordExpform = pordExpform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_LETTCRED
     *
     * @return the value of MDST.PORDER.PORD_LETTCRED
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordLettcred() {
        return pordLettcred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_LETTCRED
     *
     * @param pordLettcred the value for MDST.PORDER.PORD_LETTCRED
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordLettcred(String pordLettcred) {
        this.pordLettcred = pordLettcred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SECURITY
     *
     * @return the value of MDST.PORDER.PORD_SECURITY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSecurity() {
        return pordSecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SECURITY
     *
     * @param pordSecurity the value for MDST.PORDER.PORD_SECURITY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSecurity(String pordSecurity) {
        this.pordSecurity = pordSecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_REF1
     *
     * @return the value of MDST.PORDER.PORD_REF1
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordRef1() {
        return pordRef1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_REF1
     *
     * @param pordRef1 the value for MDST.PORDER.PORD_REF1
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordRef1(String pordRef1) {
        this.pordRef1 = pordRef1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_REF2
     *
     * @return the value of MDST.PORDER.PORD_REF2
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordRef2() {
        return pordRef2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_REF2
     *
     * @param pordRef2 the value for MDST.PORDER.PORD_REF2
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordRef2(String pordRef2) {
        this.pordRef2 = pordRef2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_DELTERM
     *
     * @return the value of MDST.PORDER.PORD_DELTERM
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordDelterm() {
        return pordDelterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_DELTERM
     *
     * @param pordDelterm the value for MDST.PORDER.PORD_DELTERM
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordDelterm(String pordDelterm) {
        this.pordDelterm = pordDelterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SPECDEAL
     *
     * @return the value of MDST.PORDER.PORD_SPECDEAL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSpecdeal() {
        return pordSpecdeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SPECDEAL
     *
     * @param pordSpecdeal the value for MDST.PORDER.PORD_SPECDEAL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSpecdeal(String pordSpecdeal) {
        this.pordSpecdeal = pordSpecdeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_CUSTOMER
     *
     * @return the value of MDST.PORDER.PORD_CUSTOMER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordCustomer() {
        return pordCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_CUSTOMER
     *
     * @param pordCustomer the value for MDST.PORDER.PORD_CUSTOMER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCustomer(String pordCustomer) {
        this.pordCustomer = pordCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SUPPREF
     *
     * @return the value of MDST.PORDER.PORD_SUPPREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSuppref() {
        return pordSuppref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SUPPREF
     *
     * @param pordSuppref the value for MDST.PORDER.PORD_SUPPREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSuppref(String pordSuppref) {
        this.pordSuppref = pordSuppref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_COMPANY
     *
     * @return the value of MDST.PORDER.PORD_COMPANY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordCompany() {
        return pordCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_COMPANY
     *
     * @param pordCompany the value for MDST.PORDER.PORD_COMPANY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCompany(String pordCompany) {
        this.pordCompany = pordCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SUPNDCODE
     *
     * @return the value of MDST.PORDER.PORD_SUPNDCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSupndcode() {
        return pordSupndcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SUPNDCODE
     *
     * @param pordSupndcode the value for MDST.PORDER.PORD_SUPNDCODE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSupndcode(String pordSupndcode) {
        this.pordSupndcode = pordSupndcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_DIRLOC
     *
     * @return the value of MDST.PORDER.PORD_DIRLOC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordDirloc() {
        return pordDirloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_DIRLOC
     *
     * @param pordDirloc the value for MDST.PORDER.PORD_DIRLOC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordDirloc(String pordDirloc) {
        this.pordDirloc = pordDirloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ESN
     *
     * @return the value of MDST.PORDER.PORD_ESN
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Long getPordEsn() {
        return pordEsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ESN
     *
     * @param pordEsn the value for MDST.PORDER.PORD_ESN
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordEsn(Long pordEsn) {
        this.pordEsn = pordEsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ESSEQ
     *
     * @return the value of MDST.PORDER.PORD_ESSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Integer getPordEsseq() {
        return pordEsseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ESSEQ
     *
     * @param pordEsseq the value for MDST.PORDER.PORD_ESSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordEsseq(Integer pordEsseq) {
        this.pordEsseq = pordEsseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_CCOMP
     *
     * @return the value of MDST.PORDER.PORD_CCOMP
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordCcomp() {
        return pordCcomp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_CCOMP
     *
     * @param pordCcomp the value for MDST.PORDER.PORD_CCOMP
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCcomp(String pordCcomp) {
        this.pordCcomp = pordCcomp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SHIPMETH
     *
     * @return the value of MDST.PORDER.PORD_SHIPMETH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordShipmeth() {
        return pordShipmeth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SHIPMETH
     *
     * @param pordShipmeth the value for MDST.PORDER.PORD_SHIPMETH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordShipmeth(String pordShipmeth) {
        this.pordShipmeth = pordShipmeth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_CURRENCY
     *
     * @return the value of MDST.PORDER.PORD_CURRENCY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordCurrency() {
        return pordCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_CURRENCY
     *
     * @param pordCurrency the value for MDST.PORDER.PORD_CURRENCY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCurrency(String pordCurrency) {
        this.pordCurrency = pordCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_PRCOPIES
     *
     * @return the value of MDST.PORDER.PORD_PRCOPIES
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Long getPordPrcopies() {
        return pordPrcopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_PRCOPIES
     *
     * @param pordPrcopies the value for MDST.PORDER.PORD_PRCOPIES
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordPrcopies(Long pordPrcopies) {
        this.pordPrcopies = pordPrcopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_REPREF
     *
     * @return the value of MDST.PORDER.PORD_REPREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordRepref() {
        return pordRepref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_REPREF
     *
     * @param pordRepref the value for MDST.PORDER.PORD_REPREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordRepref(String pordRepref) {
        this.pordRepref = pordRepref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ACKSTATUS
     *
     * @return the value of MDST.PORDER.PORD_ACKSTATUS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordAckstatus() {
        return pordAckstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ACKSTATUS
     *
     * @param pordAckstatus the value for MDST.PORDER.PORD_ACKSTATUS
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordAckstatus(String pordAckstatus) {
        this.pordAckstatus = pordAckstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_PIGRP
     *
     * @return the value of MDST.PORDER.PORD_PIGRP
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordPigrp() {
        return pordPigrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_PIGRP
     *
     * @param pordPigrp the value for MDST.PORDER.PORD_PIGRP
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordPigrp(String pordPigrp) {
        this.pordPigrp = pordPigrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_FPREG
     *
     * @return the value of MDST.PORDER.PORD_FPREG
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordFpreg() {
        return pordFpreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_FPREG
     *
     * @param pordFpreg the value for MDST.PORDER.PORD_FPREG
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordFpreg(String pordFpreg) {
        this.pordFpreg = pordFpreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SUPPSTAT
     *
     * @return the value of MDST.PORDER.PORD_SUPPSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSuppstat() {
        return pordSuppstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SUPPSTAT
     *
     * @param pordSuppstat the value for MDST.PORDER.PORD_SUPPSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSuppstat(String pordSuppstat) {
        this.pordSuppstat = pordSuppstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_LASTAMEND
     *
     * @return the value of MDST.PORDER.PORD_LASTAMEND
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Date getPordLastamend() {
        return pordLastamend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_LASTAMEND
     *
     * @param pordLastamend the value for MDST.PORDER.PORD_LASTAMEND
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordLastamend(Date pordLastamend) {
        this.pordLastamend = pordLastamend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_CALL
     *
     * @return the value of MDST.PORDER.PORD_CALL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordCall() {
        return pordCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_CALL
     *
     * @param pordCall the value for MDST.PORDER.PORD_CALL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCall(String pordCall) {
        this.pordCall = pordCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_IRREF
     *
     * @return the value of MDST.PORDER.PORD_IRREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordIrref() {
        return pordIrref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_IRREF
     *
     * @param pordIrref the value for MDST.PORDER.PORD_IRREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordIrref(String pordIrref) {
        this.pordIrref = pordIrref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SUBPOST
     *
     * @return the value of MDST.PORDER.PORD_SUBPOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSubpost() {
        return pordSubpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SUBPOST
     *
     * @param pordSubpost the value for MDST.PORDER.PORD_SUBPOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSubpost(String pordSubpost) {
        this.pordSubpost = pordSubpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_NOINV
     *
     * @return the value of MDST.PORDER.PORD_NOINV
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordNoinv() {
        return pordNoinv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_NOINV
     *
     * @param pordNoinv the value for MDST.PORDER.PORD_NOINV
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordNoinv(String pordNoinv) {
        this.pordNoinv = pordNoinv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_CALLALNK
     *
     * @return the value of MDST.PORDER.PORD_CALLALNK
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordCallalnk() {
        return pordCallalnk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_CALLALNK
     *
     * @param pordCallalnk the value for MDST.PORDER.PORD_CALLALNK
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCallalnk(String pordCallalnk) {
        this.pordCallalnk = pordCallalnk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_MEFFDATE
     *
     * @return the value of MDST.PORDER.PORD_MEFFDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Date getPordMeffdate() {
        return pordMeffdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_MEFFDATE
     *
     * @param pordMeffdate the value for MDST.PORDER.PORD_MEFFDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordMeffdate(Date pordMeffdate) {
        this.pordMeffdate = pordMeffdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_MEXPDATE
     *
     * @return the value of MDST.PORDER.PORD_MEXPDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Date getPordMexpdate() {
        return pordMexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_MEXPDATE
     *
     * @param pordMexpdate the value for MDST.PORDER.PORD_MEXPDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordMexpdate(Date pordMexpdate) {
        this.pordMexpdate = pordMexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SUPMREF
     *
     * @return the value of MDST.PORDER.PORD_SUPMREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSupmref() {
        return pordSupmref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SUPMREF
     *
     * @param pordSupmref the value for MDST.PORDER.PORD_SUPMREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSupmref(String pordSupmref) {
        this.pordSupmref = pordSupmref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SUPMDESC
     *
     * @return the value of MDST.PORDER.PORD_SUPMDESC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSupmdesc() {
        return pordSupmdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SUPMDESC
     *
     * @param pordSupmdesc the value for MDST.PORDER.PORD_SUPMDESC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSupmdesc(String pordSupmdesc) {
        this.pordSupmdesc = pordSupmdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ULOC
     *
     * @return the value of MDST.PORDER.PORD_ULOC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordUloc() {
        return pordUloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ULOC
     *
     * @param pordUloc the value for MDST.PORDER.PORD_ULOC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordUloc(String pordUloc) {
        this.pordUloc = pordUloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_FAX
     *
     * @return the value of MDST.PORDER.PORD_FAX
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordFax() {
        return pordFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_FAX
     *
     * @param pordFax the value for MDST.PORDER.PORD_FAX
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordFax(String pordFax) {
        this.pordFax = pordFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_EMAIL
     *
     * @return the value of MDST.PORDER.PORD_EMAIL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordEmail() {
        return pordEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_EMAIL
     *
     * @param pordEmail the value for MDST.PORDER.PORD_EMAIL
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordEmail(String pordEmail) {
        this.pordEmail = pordEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_ORDTYPE
     *
     * @return the value of MDST.PORDER.PORD_ORDTYPE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordOrdtype() {
        return pordOrdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_ORDTYPE
     *
     * @param pordOrdtype the value for MDST.PORDER.PORD_ORDTYPE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordOrdtype(String pordOrdtype) {
        this.pordOrdtype = pordOrdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_POROUTE
     *
     * @return the value of MDST.PORDER.PORD_POROUTE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordPoroute() {
        return pordPoroute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_POROUTE
     *
     * @param pordPoroute the value for MDST.PORDER.PORD_POROUTE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordPoroute(String pordPoroute) {
        this.pordPoroute = pordPoroute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_CONTACT
     *
     * @return the value of MDST.PORDER.PORD_CONTACT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordContact() {
        return pordContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_CONTACT
     *
     * @param pordContact the value for MDST.PORDER.PORD_CONTACT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordContact(String pordContact) {
        this.pordContact = pordContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_CONREF
     *
     * @return the value of MDST.PORDER.PORD_CONREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordConref() {
        return pordConref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_CONREF
     *
     * @param pordConref the value for MDST.PORDER.PORD_CONREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordConref(String pordConref) {
        this.pordConref = pordConref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_POLIMIT
     *
     * @return the value of MDST.PORDER.PORD_POLIMIT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordPolimit() {
        return pordPolimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_POLIMIT
     *
     * @param pordPolimit the value for MDST.PORDER.PORD_POLIMIT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordPolimit(String pordPolimit) {
        this.pordPolimit = pordPolimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_SENT
     *
     * @return the value of MDST.PORDER.PORD_SENT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordSent() {
        return pordSent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_SENT
     *
     * @param pordSent the value for MDST.PORDER.PORD_SENT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordSent(String pordSent) {
        this.pordSent = pordSent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.PORDER.PORD_CAREF
     *
     * @return the value of MDST.PORDER.PORD_CAREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getPordCaref() {
        return pordCaref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.PORDER.PORD_CAREF
     *
     * @param pordCaref the value for MDST.PORDER.PORD_CAREF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setPordCaref(String pordCaref) {
        this.pordCaref = pordCaref;
    }
}