package au.com.jaycar.warehouse.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_PRODUCT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String stkProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_LOC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String stkLoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_STKQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkStkqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_VALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_AVCOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkAvcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_MINQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkMinqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_REORDER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkReorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_MAXQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkMaxqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_ORIGCOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkOrigcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_LATECOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkLatecost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_OSPURCH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkOspurch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_CHDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private Date stkChdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_CHCAT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private String stkChcat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_WHATIF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkWhatif;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_ALLSTK
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkAllstk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_BACKORD
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    private BigDecimal stkBackord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_FWDORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkFwdord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_CALQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkCalqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_LASTSALE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Date stkLastsale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_QUOTORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkQuotord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_BUYER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_NEXTSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Long stkNextseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_FIFOSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Long stkFifoseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_BINREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkBinref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_AVVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkAvval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_FIVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkFival;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_LASTPURCH
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Date stkLastpurch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_LASTMOV
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Date stkLastmov;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_ORDSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkOrdstat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_OSWOP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkOswop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_UNAVQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkUnavqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_OSITR
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkOsitr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_PICKBIN
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkPickbin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_ZONE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkZone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_RESVPO
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkResvpo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_CAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkCat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_CREDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Date stkCredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_MANCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkMancat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_INSPBIN
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkInspbin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_HOLDBIN
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkHoldbin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_RESQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkResqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_BASFIVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkBasfival;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_BASAVVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkBasavval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_BASEVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkBaseval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_ISLQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkIslqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_ISLDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Date stkIsldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_LINKQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkLinkqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_FPADJ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkFpadj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_CCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkCcat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_MANCCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkManccat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_PBSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkPbstat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_ORDCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkOrdcat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_ORDMANCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkOrdmancat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_CYCLECNT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkCyclecnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_PROJCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkProjcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_SUPPLIER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkSupplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_PRCLAS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkPrclas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_WHCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkWhcat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_SDENSITY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkSdensity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_UNVALLQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkUnvallqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_ASSOCQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal stkAssocqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.STOCK.STK_SUPPCOMP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String stkSuppcomp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_PRODUCT
     *
     * @return the value of MDST.STOCK.STK_PRODUCT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    
    private Cmprod cmprod;
    
    
    public Cmprod getCmprod() {
		return cmprod;
	}

	public void setCmprod(Cmprod cmprod) {
		this.cmprod = cmprod;
	}

	public String getStkProduct() {
        return stkProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_PRODUCT
     *
     * @param stkProduct the value for MDST.STOCK.STK_PRODUCT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkProduct(String stkProduct) {
        this.stkProduct = stkProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_LOC
     *
     * @return the value of MDST.STOCK.STK_LOC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getStkLoc() {
        return stkLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_LOC
     *
     * @param stkLoc the value for MDST.STOCK.STK_LOC
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkLoc(String stkLoc) {
        this.stkLoc = stkLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_STKQTY
     *
     * @return the value of MDST.STOCK.STK_STKQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkStkqty() {
        return stkStkqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_STKQTY
     *
     * @param stkStkqty the value for MDST.STOCK.STK_STKQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkStkqty(BigDecimal stkStkqty) {
        this.stkStkqty = stkStkqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_VALUE
     *
     * @return the value of MDST.STOCK.STK_VALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkValue() {
        return stkValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_VALUE
     *
     * @param stkValue the value for MDST.STOCK.STK_VALUE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkValue(BigDecimal stkValue) {
        this.stkValue = stkValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_AVCOST
     *
     * @return the value of MDST.STOCK.STK_AVCOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkAvcost() {
        return stkAvcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_AVCOST
     *
     * @param stkAvcost the value for MDST.STOCK.STK_AVCOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkAvcost(BigDecimal stkAvcost) {
        this.stkAvcost = stkAvcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_MINQTY
     *
     * @return the value of MDST.STOCK.STK_MINQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkMinqty() {
        return stkMinqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_MINQTY
     *
     * @param stkMinqty the value for MDST.STOCK.STK_MINQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkMinqty(BigDecimal stkMinqty) {
        this.stkMinqty = stkMinqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_REORDER
     *
     * @return the value of MDST.STOCK.STK_REORDER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkReorder() {
        return stkReorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_REORDER
     *
     * @param stkReorder the value for MDST.STOCK.STK_REORDER
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkReorder(BigDecimal stkReorder) {
        this.stkReorder = stkReorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_MAXQTY
     *
     * @return the value of MDST.STOCK.STK_MAXQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkMaxqty() {
        return stkMaxqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_MAXQTY
     *
     * @param stkMaxqty the value for MDST.STOCK.STK_MAXQTY
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkMaxqty(BigDecimal stkMaxqty) {
        this.stkMaxqty = stkMaxqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_ORIGCOST
     *
     * @return the value of MDST.STOCK.STK_ORIGCOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkOrigcost() {
        return stkOrigcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_ORIGCOST
     *
     * @param stkOrigcost the value for MDST.STOCK.STK_ORIGCOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkOrigcost(BigDecimal stkOrigcost) {
        this.stkOrigcost = stkOrigcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_LATECOST
     *
     * @return the value of MDST.STOCK.STK_LATECOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkLatecost() {
        return stkLatecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_LATECOST
     *
     * @param stkLatecost the value for MDST.STOCK.STK_LATECOST
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkLatecost(BigDecimal stkLatecost) {
        this.stkLatecost = stkLatecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_OSPURCH
     *
     * @return the value of MDST.STOCK.STK_OSPURCH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkOspurch() {
        return stkOspurch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_OSPURCH
     *
     * @param stkOspurch the value for MDST.STOCK.STK_OSPURCH
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkOspurch(BigDecimal stkOspurch) {
        this.stkOspurch = stkOspurch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_CHDATE
     *
     * @return the value of MDST.STOCK.STK_CHDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public Date getStkChdate() {
        return stkChdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_CHDATE
     *
     * @param stkChdate the value for MDST.STOCK.STK_CHDATE
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkChdate(Date stkChdate) {
        this.stkChdate = stkChdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_CHCAT
     *
     * @return the value of MDST.STOCK.STK_CHCAT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public String getStkChcat() {
        return stkChcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_CHCAT
     *
     * @param stkChcat the value for MDST.STOCK.STK_CHCAT
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkChcat(String stkChcat) {
        this.stkChcat = stkChcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_WHATIF
     *
     * @return the value of MDST.STOCK.STK_WHATIF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkWhatif() {
        return stkWhatif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_WHATIF
     *
     * @param stkWhatif the value for MDST.STOCK.STK_WHATIF
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkWhatif(BigDecimal stkWhatif) {
        this.stkWhatif = stkWhatif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_ALLSTK
     *
     * @return the value of MDST.STOCK.STK_ALLSTK
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkAllstk() {
        return stkAllstk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_ALLSTK
     *
     * @param stkAllstk the value for MDST.STOCK.STK_ALLSTK
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkAllstk(BigDecimal stkAllstk) {
        this.stkAllstk = stkAllstk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_BACKORD
     *
     * @return the value of MDST.STOCK.STK_BACKORD
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public BigDecimal getStkBackord() {
        return stkBackord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_BACKORD
     *
     * @param stkBackord the value for MDST.STOCK.STK_BACKORD
     *
     * @mbg.generated Wed Oct 11 11:53:15 AEDT 2017
     */
    public void setStkBackord(BigDecimal stkBackord) {
        this.stkBackord = stkBackord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_FWDORD
     *
     * @return the value of MDST.STOCK.STK_FWDORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkFwdord() {
        return stkFwdord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_FWDORD
     *
     * @param stkFwdord the value for MDST.STOCK.STK_FWDORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkFwdord(BigDecimal stkFwdord) {
        this.stkFwdord = stkFwdord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_CALQTY
     *
     * @return the value of MDST.STOCK.STK_CALQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkCalqty() {
        return stkCalqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_CALQTY
     *
     * @param stkCalqty the value for MDST.STOCK.STK_CALQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkCalqty(BigDecimal stkCalqty) {
        this.stkCalqty = stkCalqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_LASTSALE
     *
     * @return the value of MDST.STOCK.STK_LASTSALE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Date getStkLastsale() {
        return stkLastsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_LASTSALE
     *
     * @param stkLastsale the value for MDST.STOCK.STK_LASTSALE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkLastsale(Date stkLastsale) {
        this.stkLastsale = stkLastsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_QUOTORD
     *
     * @return the value of MDST.STOCK.STK_QUOTORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkQuotord() {
        return stkQuotord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_QUOTORD
     *
     * @param stkQuotord the value for MDST.STOCK.STK_QUOTORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkQuotord(BigDecimal stkQuotord) {
        this.stkQuotord = stkQuotord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_BUYER
     *
     * @return the value of MDST.STOCK.STK_BUYER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkBuyer() {
        return stkBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_BUYER
     *
     * @param stkBuyer the value for MDST.STOCK.STK_BUYER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkBuyer(String stkBuyer) {
        this.stkBuyer = stkBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_NEXTSEQ
     *
     * @return the value of MDST.STOCK.STK_NEXTSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Long getStkNextseq() {
        return stkNextseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_NEXTSEQ
     *
     * @param stkNextseq the value for MDST.STOCK.STK_NEXTSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkNextseq(Long stkNextseq) {
        this.stkNextseq = stkNextseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_FIFOSEQ
     *
     * @return the value of MDST.STOCK.STK_FIFOSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Long getStkFifoseq() {
        return stkFifoseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_FIFOSEQ
     *
     * @param stkFifoseq the value for MDST.STOCK.STK_FIFOSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkFifoseq(Long stkFifoseq) {
        this.stkFifoseq = stkFifoseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_BINREF
     *
     * @return the value of MDST.STOCK.STK_BINREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkBinref() {
        return stkBinref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_BINREF
     *
     * @param stkBinref the value for MDST.STOCK.STK_BINREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkBinref(String stkBinref) {
        this.stkBinref = stkBinref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_AVVAL
     *
     * @return the value of MDST.STOCK.STK_AVVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkAvval() {
        return stkAvval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_AVVAL
     *
     * @param stkAvval the value for MDST.STOCK.STK_AVVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkAvval(BigDecimal stkAvval) {
        this.stkAvval = stkAvval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_FIVAL
     *
     * @return the value of MDST.STOCK.STK_FIVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkFival() {
        return stkFival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_FIVAL
     *
     * @param stkFival the value for MDST.STOCK.STK_FIVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkFival(BigDecimal stkFival) {
        this.stkFival = stkFival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_LASTPURCH
     *
     * @return the value of MDST.STOCK.STK_LASTPURCH
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Date getStkLastpurch() {
        return stkLastpurch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_LASTPURCH
     *
     * @param stkLastpurch the value for MDST.STOCK.STK_LASTPURCH
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkLastpurch(Date stkLastpurch) {
        this.stkLastpurch = stkLastpurch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_LASTMOV
     *
     * @return the value of MDST.STOCK.STK_LASTMOV
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Date getStkLastmov() {
        return stkLastmov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_LASTMOV
     *
     * @param stkLastmov the value for MDST.STOCK.STK_LASTMOV
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkLastmov(Date stkLastmov) {
        this.stkLastmov = stkLastmov;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_ORDSTAT
     *
     * @return the value of MDST.STOCK.STK_ORDSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkOrdstat() {
        return stkOrdstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_ORDSTAT
     *
     * @param stkOrdstat the value for MDST.STOCK.STK_ORDSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkOrdstat(String stkOrdstat) {
        this.stkOrdstat = stkOrdstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_OSWOP
     *
     * @return the value of MDST.STOCK.STK_OSWOP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkOswop() {
        return stkOswop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_OSWOP
     *
     * @param stkOswop the value for MDST.STOCK.STK_OSWOP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkOswop(BigDecimal stkOswop) {
        this.stkOswop = stkOswop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_UNAVQTY
     *
     * @return the value of MDST.STOCK.STK_UNAVQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkUnavqty() {
        return stkUnavqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_UNAVQTY
     *
     * @param stkUnavqty the value for MDST.STOCK.STK_UNAVQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkUnavqty(BigDecimal stkUnavqty) {
        this.stkUnavqty = stkUnavqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_OSITR
     *
     * @return the value of MDST.STOCK.STK_OSITR
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkOsitr() {
        return stkOsitr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_OSITR
     *
     * @param stkOsitr the value for MDST.STOCK.STK_OSITR
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkOsitr(BigDecimal stkOsitr) {
        this.stkOsitr = stkOsitr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_PICKBIN
     *
     * @return the value of MDST.STOCK.STK_PICKBIN
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkPickbin() {
        return stkPickbin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_PICKBIN
     *
     * @param stkPickbin the value for MDST.STOCK.STK_PICKBIN
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkPickbin(String stkPickbin) {
        this.stkPickbin = stkPickbin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_ZONE
     *
     * @return the value of MDST.STOCK.STK_ZONE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkZone() {
        return stkZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_ZONE
     *
     * @param stkZone the value for MDST.STOCK.STK_ZONE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkZone(String stkZone) {
        this.stkZone = stkZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_RESVPO
     *
     * @return the value of MDST.STOCK.STK_RESVPO
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkResvpo() {
        return stkResvpo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_RESVPO
     *
     * @param stkResvpo the value for MDST.STOCK.STK_RESVPO
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkResvpo(BigDecimal stkResvpo) {
        this.stkResvpo = stkResvpo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_CAT
     *
     * @return the value of MDST.STOCK.STK_CAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkCat() {
        return stkCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_CAT
     *
     * @param stkCat the value for MDST.STOCK.STK_CAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkCat(String stkCat) {
        this.stkCat = stkCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_CREDATE
     *
     * @return the value of MDST.STOCK.STK_CREDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Date getStkCredate() {
        return stkCredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_CREDATE
     *
     * @param stkCredate the value for MDST.STOCK.STK_CREDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkCredate(Date stkCredate) {
        this.stkCredate = stkCredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_MANCAT
     *
     * @return the value of MDST.STOCK.STK_MANCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkMancat() {
        return stkMancat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_MANCAT
     *
     * @param stkMancat the value for MDST.STOCK.STK_MANCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkMancat(String stkMancat) {
        this.stkMancat = stkMancat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_INSPBIN
     *
     * @return the value of MDST.STOCK.STK_INSPBIN
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkInspbin() {
        return stkInspbin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_INSPBIN
     *
     * @param stkInspbin the value for MDST.STOCK.STK_INSPBIN
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkInspbin(String stkInspbin) {
        this.stkInspbin = stkInspbin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_HOLDBIN
     *
     * @return the value of MDST.STOCK.STK_HOLDBIN
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkHoldbin() {
        return stkHoldbin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_HOLDBIN
     *
     * @param stkHoldbin the value for MDST.STOCK.STK_HOLDBIN
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkHoldbin(String stkHoldbin) {
        this.stkHoldbin = stkHoldbin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_RESQTY
     *
     * @return the value of MDST.STOCK.STK_RESQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkResqty() {
        return stkResqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_RESQTY
     *
     * @param stkResqty the value for MDST.STOCK.STK_RESQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkResqty(BigDecimal stkResqty) {
        this.stkResqty = stkResqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_BASFIVAL
     *
     * @return the value of MDST.STOCK.STK_BASFIVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkBasfival() {
        return stkBasfival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_BASFIVAL
     *
     * @param stkBasfival the value for MDST.STOCK.STK_BASFIVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkBasfival(BigDecimal stkBasfival) {
        this.stkBasfival = stkBasfival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_BASAVVAL
     *
     * @return the value of MDST.STOCK.STK_BASAVVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkBasavval() {
        return stkBasavval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_BASAVVAL
     *
     * @param stkBasavval the value for MDST.STOCK.STK_BASAVVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkBasavval(BigDecimal stkBasavval) {
        this.stkBasavval = stkBasavval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_BASEVAL
     *
     * @return the value of MDST.STOCK.STK_BASEVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkBaseval() {
        return stkBaseval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_BASEVAL
     *
     * @param stkBaseval the value for MDST.STOCK.STK_BASEVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkBaseval(BigDecimal stkBaseval) {
        this.stkBaseval = stkBaseval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_ISLQTY
     *
     * @return the value of MDST.STOCK.STK_ISLQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkIslqty() {
        return stkIslqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_ISLQTY
     *
     * @param stkIslqty the value for MDST.STOCK.STK_ISLQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkIslqty(BigDecimal stkIslqty) {
        this.stkIslqty = stkIslqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_ISLDATE
     *
     * @return the value of MDST.STOCK.STK_ISLDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Date getStkIsldate() {
        return stkIsldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_ISLDATE
     *
     * @param stkIsldate the value for MDST.STOCK.STK_ISLDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkIsldate(Date stkIsldate) {
        this.stkIsldate = stkIsldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_LINKQTY
     *
     * @return the value of MDST.STOCK.STK_LINKQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkLinkqty() {
        return stkLinkqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_LINKQTY
     *
     * @param stkLinkqty the value for MDST.STOCK.STK_LINKQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkLinkqty(BigDecimal stkLinkqty) {
        this.stkLinkqty = stkLinkqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_FPADJ
     *
     * @return the value of MDST.STOCK.STK_FPADJ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkFpadj() {
        return stkFpadj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_FPADJ
     *
     * @param stkFpadj the value for MDST.STOCK.STK_FPADJ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkFpadj(BigDecimal stkFpadj) {
        this.stkFpadj = stkFpadj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_CCAT
     *
     * @return the value of MDST.STOCK.STK_CCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkCcat() {
        return stkCcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_CCAT
     *
     * @param stkCcat the value for MDST.STOCK.STK_CCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkCcat(String stkCcat) {
        this.stkCcat = stkCcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_MANCCAT
     *
     * @return the value of MDST.STOCK.STK_MANCCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkManccat() {
        return stkManccat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_MANCCAT
     *
     * @param stkManccat the value for MDST.STOCK.STK_MANCCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkManccat(String stkManccat) {
        this.stkManccat = stkManccat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_PBSTAT
     *
     * @return the value of MDST.STOCK.STK_PBSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkPbstat() {
        return stkPbstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_PBSTAT
     *
     * @param stkPbstat the value for MDST.STOCK.STK_PBSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkPbstat(String stkPbstat) {
        this.stkPbstat = stkPbstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_ORDCAT
     *
     * @return the value of MDST.STOCK.STK_ORDCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkOrdcat() {
        return stkOrdcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_ORDCAT
     *
     * @param stkOrdcat the value for MDST.STOCK.STK_ORDCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkOrdcat(String stkOrdcat) {
        this.stkOrdcat = stkOrdcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_ORDMANCAT
     *
     * @return the value of MDST.STOCK.STK_ORDMANCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkOrdmancat() {
        return stkOrdmancat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_ORDMANCAT
     *
     * @param stkOrdmancat the value for MDST.STOCK.STK_ORDMANCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkOrdmancat(String stkOrdmancat) {
        this.stkOrdmancat = stkOrdmancat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_CYCLECNT
     *
     * @return the value of MDST.STOCK.STK_CYCLECNT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkCyclecnt() {
        return stkCyclecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_CYCLECNT
     *
     * @param stkCyclecnt the value for MDST.STOCK.STK_CYCLECNT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkCyclecnt(String stkCyclecnt) {
        this.stkCyclecnt = stkCyclecnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_PROJCODE
     *
     * @return the value of MDST.STOCK.STK_PROJCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkProjcode() {
        return stkProjcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_PROJCODE
     *
     * @param stkProjcode the value for MDST.STOCK.STK_PROJCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkProjcode(String stkProjcode) {
        this.stkProjcode = stkProjcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_SUPPLIER
     *
     * @return the value of MDST.STOCK.STK_SUPPLIER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkSupplier() {
        return stkSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_SUPPLIER
     *
     * @param stkSupplier the value for MDST.STOCK.STK_SUPPLIER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkSupplier(String stkSupplier) {
        this.stkSupplier = stkSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_PRCLAS
     *
     * @return the value of MDST.STOCK.STK_PRCLAS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkPrclas() {
        return stkPrclas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_PRCLAS
     *
     * @param stkPrclas the value for MDST.STOCK.STK_PRCLAS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkPrclas(String stkPrclas) {
        this.stkPrclas = stkPrclas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_WHCAT
     *
     * @return the value of MDST.STOCK.STK_WHCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkWhcat() {
        return stkWhcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_WHCAT
     *
     * @param stkWhcat the value for MDST.STOCK.STK_WHCAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkWhcat(String stkWhcat) {
        this.stkWhcat = stkWhcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_SDENSITY
     *
     * @return the value of MDST.STOCK.STK_SDENSITY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkSdensity() {
        return stkSdensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_SDENSITY
     *
     * @param stkSdensity the value for MDST.STOCK.STK_SDENSITY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkSdensity(BigDecimal stkSdensity) {
        this.stkSdensity = stkSdensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_UNVALLQTY
     *
     * @return the value of MDST.STOCK.STK_UNVALLQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkUnvallqty() {
        return stkUnvallqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_UNVALLQTY
     *
     * @param stkUnvallqty the value for MDST.STOCK.STK_UNVALLQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkUnvallqty(BigDecimal stkUnvallqty) {
        this.stkUnvallqty = stkUnvallqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_ASSOCQTY
     *
     * @return the value of MDST.STOCK.STK_ASSOCQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getStkAssocqty() {
        return stkAssocqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_ASSOCQTY
     *
     * @param stkAssocqty the value for MDST.STOCK.STK_ASSOCQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkAssocqty(BigDecimal stkAssocqty) {
        this.stkAssocqty = stkAssocqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.STOCK.STK_SUPPCOMP
     *
     * @return the value of MDST.STOCK.STK_SUPPCOMP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getStkSuppcomp() {
        return stkSuppcomp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.STOCK.STK_SUPPCOMP
     *
     * @param stkSuppcomp the value for MDST.STOCK.STK_SUPPCOMP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setStkSuppcomp(String stkSuppcomp) {
        this.stkSuppcomp = stkSuppcomp;
    }
}