package au.com.jaycar.warehouse.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Wohead {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_ORDREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohOrdref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_ORDVER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Integer wohOrdver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_USERID
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_DATEORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Date wohDateord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_WORKREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohWorkref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_NODEL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohNodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_AUTHOR
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_COSTMETH
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohCostmeth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_COSTCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohCostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_WT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohWt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_SUBCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohSubcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_CURCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohCurcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_COMCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohComcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_TYPE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_PSTATUS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohPstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_STATUS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_SRCLOC
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohSrcloc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_ORDVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohOrdval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_ORDCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohOrdcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_PRODUCT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_TOTQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohTotqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_PRODQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohProdqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_REMQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohRemqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_REMWIP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohRemwip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_REJECTS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohRejects;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_ATYPE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohAtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_BILLNAME
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohBillname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_VARIANT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohVariant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_SOWOFLG
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohSowoflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_SOORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohSoord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_SOQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohSoqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_SOSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Integer wohSoseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_DATEREQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Date wohDatereq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_STARTDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Date wohStartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_STARTSHFT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohStartshft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_COMPDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Date wohCompdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_DEPT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_SECTION
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohSection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_STOCKDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Date wohStockdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_WRKLOC
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohWrkloc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_PRIORITY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohPriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_DURATION
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Integer wohDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_NEWORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohNeword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_BATREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohBatref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_TCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Long wohTcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_CURFIX
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohCurfix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_EXTRACTED
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohExtracted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_PRODDESC
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohProddesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_SELLPR
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohSellpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_PROVER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohProver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_MAKQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohMakqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_COMPANY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_PIGRP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohPigrp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_RECRET
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohRecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_HOLD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohHold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_ALLSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohAllstat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_PROJREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohProjref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_INITWO
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohInitwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_ESTCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohEstcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_ROLLING
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohRolling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_REJCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohRejcost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_DISSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private Long wohDisseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_STARTTIME
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_COMPTIME
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private BigDecimal wohComptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_FPREG
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohFpreg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_CUSTOMER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohCustomer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MDST.WOHEAD.WOH_CUSTCOMP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    private String wohCustcomp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_ORDREF
     *
     * @return the value of MDST.WOHEAD.WOH_ORDREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohOrdref() {
        return wohOrdref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_ORDREF
     *
     * @param wohOrdref the value for MDST.WOHEAD.WOH_ORDREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohOrdref(String wohOrdref) {
        this.wohOrdref = wohOrdref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_ORDVER
     *
     * @return the value of MDST.WOHEAD.WOH_ORDVER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Integer getWohOrdver() {
        return wohOrdver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_ORDVER
     *
     * @param wohOrdver the value for MDST.WOHEAD.WOH_ORDVER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohOrdver(Integer wohOrdver) {
        this.wohOrdver = wohOrdver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_USERID
     *
     * @return the value of MDST.WOHEAD.WOH_USERID
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohUserid() {
        return wohUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_USERID
     *
     * @param wohUserid the value for MDST.WOHEAD.WOH_USERID
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohUserid(String wohUserid) {
        this.wohUserid = wohUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_DATEORD
     *
     * @return the value of MDST.WOHEAD.WOH_DATEORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Date getWohDateord() {
        return wohDateord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_DATEORD
     *
     * @param wohDateord the value for MDST.WOHEAD.WOH_DATEORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohDateord(Date wohDateord) {
        this.wohDateord = wohDateord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_WORKREF
     *
     * @return the value of MDST.WOHEAD.WOH_WORKREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohWorkref() {
        return wohWorkref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_WORKREF
     *
     * @param wohWorkref the value for MDST.WOHEAD.WOH_WORKREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohWorkref(String wohWorkref) {
        this.wohWorkref = wohWorkref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_NODEL
     *
     * @return the value of MDST.WOHEAD.WOH_NODEL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohNodel() {
        return wohNodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_NODEL
     *
     * @param wohNodel the value for MDST.WOHEAD.WOH_NODEL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohNodel(String wohNodel) {
        this.wohNodel = wohNodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_AUTHOR
     *
     * @return the value of MDST.WOHEAD.WOH_AUTHOR
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohAuthor() {
        return wohAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_AUTHOR
     *
     * @param wohAuthor the value for MDST.WOHEAD.WOH_AUTHOR
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohAuthor(String wohAuthor) {
        this.wohAuthor = wohAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_COSTMETH
     *
     * @return the value of MDST.WOHEAD.WOH_COSTMETH
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohCostmeth() {
        return wohCostmeth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_COSTMETH
     *
     * @param wohCostmeth the value for MDST.WOHEAD.WOH_COSTMETH
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohCostmeth(String wohCostmeth) {
        this.wohCostmeth = wohCostmeth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_COSTCODE
     *
     * @return the value of MDST.WOHEAD.WOH_COSTCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohCostcode() {
        return wohCostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_COSTCODE
     *
     * @param wohCostcode the value for MDST.WOHEAD.WOH_COSTCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohCostcode(String wohCostcode) {
        this.wohCostcode = wohCostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_WT
     *
     * @return the value of MDST.WOHEAD.WOH_WT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohWt() {
        return wohWt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_WT
     *
     * @param wohWt the value for MDST.WOHEAD.WOH_WT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohWt(String wohWt) {
        this.wohWt = wohWt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_SUBCODE
     *
     * @return the value of MDST.WOHEAD.WOH_SUBCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohSubcode() {
        return wohSubcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_SUBCODE
     *
     * @param wohSubcode the value for MDST.WOHEAD.WOH_SUBCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohSubcode(String wohSubcode) {
        this.wohSubcode = wohSubcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_CURCOST
     *
     * @return the value of MDST.WOHEAD.WOH_CURCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohCurcost() {
        return wohCurcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_CURCOST
     *
     * @param wohCurcost the value for MDST.WOHEAD.WOH_CURCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohCurcost(BigDecimal wohCurcost) {
        this.wohCurcost = wohCurcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_COMCOST
     *
     * @return the value of MDST.WOHEAD.WOH_COMCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohComcost() {
        return wohComcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_COMCOST
     *
     * @param wohComcost the value for MDST.WOHEAD.WOH_COMCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohComcost(BigDecimal wohComcost) {
        this.wohComcost = wohComcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_TYPE
     *
     * @return the value of MDST.WOHEAD.WOH_TYPE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohType() {
        return wohType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_TYPE
     *
     * @param wohType the value for MDST.WOHEAD.WOH_TYPE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohType(String wohType) {
        this.wohType = wohType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_PSTATUS
     *
     * @return the value of MDST.WOHEAD.WOH_PSTATUS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohPstatus() {
        return wohPstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_PSTATUS
     *
     * @param wohPstatus the value for MDST.WOHEAD.WOH_PSTATUS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohPstatus(String wohPstatus) {
        this.wohPstatus = wohPstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_STATUS
     *
     * @return the value of MDST.WOHEAD.WOH_STATUS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohStatus() {
        return wohStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_STATUS
     *
     * @param wohStatus the value for MDST.WOHEAD.WOH_STATUS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohStatus(String wohStatus) {
        this.wohStatus = wohStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_SRCLOC
     *
     * @return the value of MDST.WOHEAD.WOH_SRCLOC
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohSrcloc() {
        return wohSrcloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_SRCLOC
     *
     * @param wohSrcloc the value for MDST.WOHEAD.WOH_SRCLOC
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohSrcloc(String wohSrcloc) {
        this.wohSrcloc = wohSrcloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_ORDVAL
     *
     * @return the value of MDST.WOHEAD.WOH_ORDVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohOrdval() {
        return wohOrdval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_ORDVAL
     *
     * @param wohOrdval the value for MDST.WOHEAD.WOH_ORDVAL
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohOrdval(BigDecimal wohOrdval) {
        this.wohOrdval = wohOrdval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_ORDCOST
     *
     * @return the value of MDST.WOHEAD.WOH_ORDCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohOrdcost() {
        return wohOrdcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_ORDCOST
     *
     * @param wohOrdcost the value for MDST.WOHEAD.WOH_ORDCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohOrdcost(BigDecimal wohOrdcost) {
        this.wohOrdcost = wohOrdcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_PRODUCT
     *
     * @return the value of MDST.WOHEAD.WOH_PRODUCT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohProduct() {
        return wohProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_PRODUCT
     *
     * @param wohProduct the value for MDST.WOHEAD.WOH_PRODUCT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohProduct(String wohProduct) {
        this.wohProduct = wohProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_TOTQTY
     *
     * @return the value of MDST.WOHEAD.WOH_TOTQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohTotqty() {
        return wohTotqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_TOTQTY
     *
     * @param wohTotqty the value for MDST.WOHEAD.WOH_TOTQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohTotqty(BigDecimal wohTotqty) {
        this.wohTotqty = wohTotqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_PRODQTY
     *
     * @return the value of MDST.WOHEAD.WOH_PRODQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohProdqty() {
        return wohProdqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_PRODQTY
     *
     * @param wohProdqty the value for MDST.WOHEAD.WOH_PRODQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohProdqty(BigDecimal wohProdqty) {
        this.wohProdqty = wohProdqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_REMQTY
     *
     * @return the value of MDST.WOHEAD.WOH_REMQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohRemqty() {
        return wohRemqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_REMQTY
     *
     * @param wohRemqty the value for MDST.WOHEAD.WOH_REMQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohRemqty(BigDecimal wohRemqty) {
        this.wohRemqty = wohRemqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_REMWIP
     *
     * @return the value of MDST.WOHEAD.WOH_REMWIP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohRemwip() {
        return wohRemwip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_REMWIP
     *
     * @param wohRemwip the value for MDST.WOHEAD.WOH_REMWIP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohRemwip(BigDecimal wohRemwip) {
        this.wohRemwip = wohRemwip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_REJECTS
     *
     * @return the value of MDST.WOHEAD.WOH_REJECTS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohRejects() {
        return wohRejects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_REJECTS
     *
     * @param wohRejects the value for MDST.WOHEAD.WOH_REJECTS
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohRejects(BigDecimal wohRejects) {
        this.wohRejects = wohRejects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_ATYPE
     *
     * @return the value of MDST.WOHEAD.WOH_ATYPE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohAtype() {
        return wohAtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_ATYPE
     *
     * @param wohAtype the value for MDST.WOHEAD.WOH_ATYPE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohAtype(String wohAtype) {
        this.wohAtype = wohAtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_BILLNAME
     *
     * @return the value of MDST.WOHEAD.WOH_BILLNAME
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohBillname() {
        return wohBillname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_BILLNAME
     *
     * @param wohBillname the value for MDST.WOHEAD.WOH_BILLNAME
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohBillname(String wohBillname) {
        this.wohBillname = wohBillname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_VARIANT
     *
     * @return the value of MDST.WOHEAD.WOH_VARIANT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohVariant() {
        return wohVariant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_VARIANT
     *
     * @param wohVariant the value for MDST.WOHEAD.WOH_VARIANT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohVariant(String wohVariant) {
        this.wohVariant = wohVariant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_SOWOFLG
     *
     * @return the value of MDST.WOHEAD.WOH_SOWOFLG
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohSowoflg() {
        return wohSowoflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_SOWOFLG
     *
     * @param wohSowoflg the value for MDST.WOHEAD.WOH_SOWOFLG
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohSowoflg(String wohSowoflg) {
        this.wohSowoflg = wohSowoflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_SOORD
     *
     * @return the value of MDST.WOHEAD.WOH_SOORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohSoord() {
        return wohSoord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_SOORD
     *
     * @param wohSoord the value for MDST.WOHEAD.WOH_SOORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohSoord(String wohSoord) {
        this.wohSoord = wohSoord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_SOQTY
     *
     * @return the value of MDST.WOHEAD.WOH_SOQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohSoqty() {
        return wohSoqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_SOQTY
     *
     * @param wohSoqty the value for MDST.WOHEAD.WOH_SOQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohSoqty(BigDecimal wohSoqty) {
        this.wohSoqty = wohSoqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_SOSEQ
     *
     * @return the value of MDST.WOHEAD.WOH_SOSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Integer getWohSoseq() {
        return wohSoseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_SOSEQ
     *
     * @param wohSoseq the value for MDST.WOHEAD.WOH_SOSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohSoseq(Integer wohSoseq) {
        this.wohSoseq = wohSoseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_DATEREQ
     *
     * @return the value of MDST.WOHEAD.WOH_DATEREQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Date getWohDatereq() {
        return wohDatereq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_DATEREQ
     *
     * @param wohDatereq the value for MDST.WOHEAD.WOH_DATEREQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohDatereq(Date wohDatereq) {
        this.wohDatereq = wohDatereq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_STARTDATE
     *
     * @return the value of MDST.WOHEAD.WOH_STARTDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Date getWohStartdate() {
        return wohStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_STARTDATE
     *
     * @param wohStartdate the value for MDST.WOHEAD.WOH_STARTDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohStartdate(Date wohStartdate) {
        this.wohStartdate = wohStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_STARTSHFT
     *
     * @return the value of MDST.WOHEAD.WOH_STARTSHFT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohStartshft() {
        return wohStartshft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_STARTSHFT
     *
     * @param wohStartshft the value for MDST.WOHEAD.WOH_STARTSHFT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohStartshft(String wohStartshft) {
        this.wohStartshft = wohStartshft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_COMPDATE
     *
     * @return the value of MDST.WOHEAD.WOH_COMPDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Date getWohCompdate() {
        return wohCompdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_COMPDATE
     *
     * @param wohCompdate the value for MDST.WOHEAD.WOH_COMPDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohCompdate(Date wohCompdate) {
        this.wohCompdate = wohCompdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_DEPT
     *
     * @return the value of MDST.WOHEAD.WOH_DEPT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohDept() {
        return wohDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_DEPT
     *
     * @param wohDept the value for MDST.WOHEAD.WOH_DEPT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohDept(String wohDept) {
        this.wohDept = wohDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_SECTION
     *
     * @return the value of MDST.WOHEAD.WOH_SECTION
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohSection() {
        return wohSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_SECTION
     *
     * @param wohSection the value for MDST.WOHEAD.WOH_SECTION
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohSection(String wohSection) {
        this.wohSection = wohSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_STOCKDATE
     *
     * @return the value of MDST.WOHEAD.WOH_STOCKDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Date getWohStockdate() {
        return wohStockdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_STOCKDATE
     *
     * @param wohStockdate the value for MDST.WOHEAD.WOH_STOCKDATE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohStockdate(Date wohStockdate) {
        this.wohStockdate = wohStockdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_WRKLOC
     *
     * @return the value of MDST.WOHEAD.WOH_WRKLOC
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohWrkloc() {
        return wohWrkloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_WRKLOC
     *
     * @param wohWrkloc the value for MDST.WOHEAD.WOH_WRKLOC
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohWrkloc(String wohWrkloc) {
        this.wohWrkloc = wohWrkloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_PRIORITY
     *
     * @return the value of MDST.WOHEAD.WOH_PRIORITY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohPriority() {
        return wohPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_PRIORITY
     *
     * @param wohPriority the value for MDST.WOHEAD.WOH_PRIORITY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohPriority(String wohPriority) {
        this.wohPriority = wohPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_DURATION
     *
     * @return the value of MDST.WOHEAD.WOH_DURATION
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Integer getWohDuration() {
        return wohDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_DURATION
     *
     * @param wohDuration the value for MDST.WOHEAD.WOH_DURATION
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohDuration(Integer wohDuration) {
        this.wohDuration = wohDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_NEWORD
     *
     * @return the value of MDST.WOHEAD.WOH_NEWORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohNeword() {
        return wohNeword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_NEWORD
     *
     * @param wohNeword the value for MDST.WOHEAD.WOH_NEWORD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohNeword(String wohNeword) {
        this.wohNeword = wohNeword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_BATREF
     *
     * @return the value of MDST.WOHEAD.WOH_BATREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohBatref() {
        return wohBatref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_BATREF
     *
     * @param wohBatref the value for MDST.WOHEAD.WOH_BATREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohBatref(String wohBatref) {
        this.wohBatref = wohBatref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_TCODE
     *
     * @return the value of MDST.WOHEAD.WOH_TCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Long getWohTcode() {
        return wohTcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_TCODE
     *
     * @param wohTcode the value for MDST.WOHEAD.WOH_TCODE
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohTcode(Long wohTcode) {
        this.wohTcode = wohTcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_CURFIX
     *
     * @return the value of MDST.WOHEAD.WOH_CURFIX
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohCurfix() {
        return wohCurfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_CURFIX
     *
     * @param wohCurfix the value for MDST.WOHEAD.WOH_CURFIX
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohCurfix(BigDecimal wohCurfix) {
        this.wohCurfix = wohCurfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_EXTRACTED
     *
     * @return the value of MDST.WOHEAD.WOH_EXTRACTED
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohExtracted() {
        return wohExtracted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_EXTRACTED
     *
     * @param wohExtracted the value for MDST.WOHEAD.WOH_EXTRACTED
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohExtracted(String wohExtracted) {
        this.wohExtracted = wohExtracted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_PRODDESC
     *
     * @return the value of MDST.WOHEAD.WOH_PRODDESC
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohProddesc() {
        return wohProddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_PRODDESC
     *
     * @param wohProddesc the value for MDST.WOHEAD.WOH_PRODDESC
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohProddesc(String wohProddesc) {
        this.wohProddesc = wohProddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_SELLPR
     *
     * @return the value of MDST.WOHEAD.WOH_SELLPR
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohSellpr() {
        return wohSellpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_SELLPR
     *
     * @param wohSellpr the value for MDST.WOHEAD.WOH_SELLPR
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohSellpr(BigDecimal wohSellpr) {
        this.wohSellpr = wohSellpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_PROVER
     *
     * @return the value of MDST.WOHEAD.WOH_PROVER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohProver() {
        return wohProver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_PROVER
     *
     * @param wohProver the value for MDST.WOHEAD.WOH_PROVER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohProver(String wohProver) {
        this.wohProver = wohProver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_MAKQTY
     *
     * @return the value of MDST.WOHEAD.WOH_MAKQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohMakqty() {
        return wohMakqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_MAKQTY
     *
     * @param wohMakqty the value for MDST.WOHEAD.WOH_MAKQTY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohMakqty(BigDecimal wohMakqty) {
        this.wohMakqty = wohMakqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_COMPANY
     *
     * @return the value of MDST.WOHEAD.WOH_COMPANY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohCompany() {
        return wohCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_COMPANY
     *
     * @param wohCompany the value for MDST.WOHEAD.WOH_COMPANY
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohCompany(String wohCompany) {
        this.wohCompany = wohCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_PIGRP
     *
     * @return the value of MDST.WOHEAD.WOH_PIGRP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohPigrp() {
        return wohPigrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_PIGRP
     *
     * @param wohPigrp the value for MDST.WOHEAD.WOH_PIGRP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohPigrp(String wohPigrp) {
        this.wohPigrp = wohPigrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_RECRET
     *
     * @return the value of MDST.WOHEAD.WOH_RECRET
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohRecret() {
        return wohRecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_RECRET
     *
     * @param wohRecret the value for MDST.WOHEAD.WOH_RECRET
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohRecret(String wohRecret) {
        this.wohRecret = wohRecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_HOLD
     *
     * @return the value of MDST.WOHEAD.WOH_HOLD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohHold() {
        return wohHold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_HOLD
     *
     * @param wohHold the value for MDST.WOHEAD.WOH_HOLD
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohHold(String wohHold) {
        this.wohHold = wohHold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_ALLSTAT
     *
     * @return the value of MDST.WOHEAD.WOH_ALLSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohAllstat() {
        return wohAllstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_ALLSTAT
     *
     * @param wohAllstat the value for MDST.WOHEAD.WOH_ALLSTAT
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohAllstat(String wohAllstat) {
        this.wohAllstat = wohAllstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_PROJREF
     *
     * @return the value of MDST.WOHEAD.WOH_PROJREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohProjref() {
        return wohProjref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_PROJREF
     *
     * @param wohProjref the value for MDST.WOHEAD.WOH_PROJREF
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohProjref(String wohProjref) {
        this.wohProjref = wohProjref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_INITWO
     *
     * @return the value of MDST.WOHEAD.WOH_INITWO
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohInitwo() {
        return wohInitwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_INITWO
     *
     * @param wohInitwo the value for MDST.WOHEAD.WOH_INITWO
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohInitwo(String wohInitwo) {
        this.wohInitwo = wohInitwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_ESTCOST
     *
     * @return the value of MDST.WOHEAD.WOH_ESTCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohEstcost() {
        return wohEstcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_ESTCOST
     *
     * @param wohEstcost the value for MDST.WOHEAD.WOH_ESTCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohEstcost(BigDecimal wohEstcost) {
        this.wohEstcost = wohEstcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_ROLLING
     *
     * @return the value of MDST.WOHEAD.WOH_ROLLING
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohRolling() {
        return wohRolling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_ROLLING
     *
     * @param wohRolling the value for MDST.WOHEAD.WOH_ROLLING
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohRolling(String wohRolling) {
        this.wohRolling = wohRolling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_REJCOST
     *
     * @return the value of MDST.WOHEAD.WOH_REJCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohRejcost() {
        return wohRejcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_REJCOST
     *
     * @param wohRejcost the value for MDST.WOHEAD.WOH_REJCOST
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohRejcost(BigDecimal wohRejcost) {
        this.wohRejcost = wohRejcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_DISSEQ
     *
     * @return the value of MDST.WOHEAD.WOH_DISSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public Long getWohDisseq() {
        return wohDisseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_DISSEQ
     *
     * @param wohDisseq the value for MDST.WOHEAD.WOH_DISSEQ
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohDisseq(Long wohDisseq) {
        this.wohDisseq = wohDisseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_STARTTIME
     *
     * @return the value of MDST.WOHEAD.WOH_STARTTIME
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohStarttime() {
        return wohStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_STARTTIME
     *
     * @param wohStarttime the value for MDST.WOHEAD.WOH_STARTTIME
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohStarttime(BigDecimal wohStarttime) {
        this.wohStarttime = wohStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_COMPTIME
     *
     * @return the value of MDST.WOHEAD.WOH_COMPTIME
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public BigDecimal getWohComptime() {
        return wohComptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_COMPTIME
     *
     * @param wohComptime the value for MDST.WOHEAD.WOH_COMPTIME
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohComptime(BigDecimal wohComptime) {
        this.wohComptime = wohComptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_FPREG
     *
     * @return the value of MDST.WOHEAD.WOH_FPREG
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohFpreg() {
        return wohFpreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_FPREG
     *
     * @param wohFpreg the value for MDST.WOHEAD.WOH_FPREG
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohFpreg(String wohFpreg) {
        this.wohFpreg = wohFpreg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_CUSTOMER
     *
     * @return the value of MDST.WOHEAD.WOH_CUSTOMER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohCustomer() {
        return wohCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_CUSTOMER
     *
     * @param wohCustomer the value for MDST.WOHEAD.WOH_CUSTOMER
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohCustomer(String wohCustomer) {
        this.wohCustomer = wohCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MDST.WOHEAD.WOH_CUSTCOMP
     *
     * @return the value of MDST.WOHEAD.WOH_CUSTCOMP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public String getWohCustcomp() {
        return wohCustcomp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MDST.WOHEAD.WOH_CUSTCOMP
     *
     * @param wohCustcomp the value for MDST.WOHEAD.WOH_CUSTCOMP
     *
     * @mbg.generated Wed Oct 11 11:53:16 AEDT 2017
     */
    public void setWohCustcomp(String wohCustcomp) {
        this.wohCustcomp = wohCustcomp;
    }
}