/*
 * Created on 29 Sep 2017 ( Time 15:10:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package au.com.jaycar.local.persistence.services;

import java.util.List;
import java.util.Map;

import au.com.jaycar.local.entity.jpa.PolinesEntity;

/**
 * Basic persistence operations for entity "Polines"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface PolinesPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param polines
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(PolinesEntity polines) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param pk
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer pk) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param polines
	 */
	public void insert(PolinesEntity polines) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param pk
	 * @return the entity loaded (or null if not found)
	 */
	public PolinesEntity load(Integer pk) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<PolinesEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<PolinesEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<PolinesEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param polines
	 * @return
	 */
	public PolinesEntity save(PolinesEntity polines) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<PolinesEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
