package au.com.jaycar.mdm.entity;

import java.util.Date;

public class Medias {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.PK
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.hjmpTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long hjmpts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.TypePkString
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long typepkstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.createdTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Date createdts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.modifiedTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Date modifiedts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.OwnerPkString
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long ownerpkstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.aCLTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long aclts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.propTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long propts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.Mime
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String mime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.RealFileName
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String realfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_alttext
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String pAlttext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_folder
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pFolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_removable
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Boolean pRemovable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_catalogversion
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pCatalogversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_description
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String pDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_catalog
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_datapk
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pDatapk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_mediaformat
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pMediaformat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_mediacontainer
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pMediacontainer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.Code
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_size
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_outputmimetype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String pOutputmimetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_inputmimetype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String pInputmimetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_sourceitem
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pSourceitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_itemtimestamp
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Date pItemtimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_format
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_quotecharacter
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Short pQuotecharacter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_commentcharacter
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Short pCommentcharacter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_removeonsuccess
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Boolean pRemoveonsuccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_linestoskip
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pLinestoskip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_encoding
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pEncoding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_zipentry
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String pZipentry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_fieldseparator
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Short pFieldseparator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_cronjob
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pCronjob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_cronjobpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pCronjobpos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_scheduledcount
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pScheduledcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_allowscriptevaluation
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Boolean pAllowscriptevaluation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_icon
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_compiledreport
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pCompiledreport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_publicationpreviewpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pPublicationpreviewpos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_configuration
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pConfiguration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_pagepreview
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pPagepreview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_publicationpreview
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pPublicationpreview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_chapterpreview
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pChapterpreview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_chapterpreviewpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pChapterpreviewpos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_pagepreviewpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pPagepreviewpos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_celumid
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pCelumid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_binarychangedcounter
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pBinarychangedcounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_rawassetpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pRawassetpos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_parameters
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String pParameters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_deleted
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Boolean pDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_synchronized
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Boolean pSynchronized;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_assettype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pAssettype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_rawasset
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pRawasset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_fileextension
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String pFileextension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_locationhash
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String pLocationhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_subfolderpath
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String pSubfolderpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_pagepos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pPagepos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_page
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_product1nto
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pProduct1nto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_product1nfrom
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pProduct1nfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_product1nfrompos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Integer pProduct1nfrompos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_contextitem
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pContextitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_deeplinkurl
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pDeeplinkurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_barcodetype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private Long pBarcodetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medias.p_barcodetext
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    private String pBarcodetext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.PK
     *
     * @return the value of medias.PK
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.PK
     *
     * @param pk the value for medias.PK
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setPk(Long pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.hjmpTS
     *
     * @return the value of medias.hjmpTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getHjmpts() {
        return hjmpts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.hjmpTS
     *
     * @param hjmpts the value for medias.hjmpTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setHjmpts(Long hjmpts) {
        this.hjmpts = hjmpts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.TypePkString
     *
     * @return the value of medias.TypePkString
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getTypepkstring() {
        return typepkstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.TypePkString
     *
     * @param typepkstring the value for medias.TypePkString
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setTypepkstring(Long typepkstring) {
        this.typepkstring = typepkstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.createdTS
     *
     * @return the value of medias.createdTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Date getCreatedts() {
        return createdts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.createdTS
     *
     * @param createdts the value for medias.createdTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setCreatedts(Date createdts) {
        this.createdts = createdts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.modifiedTS
     *
     * @return the value of medias.modifiedTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Date getModifiedts() {
        return modifiedts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.modifiedTS
     *
     * @param modifiedts the value for medias.modifiedTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setModifiedts(Date modifiedts) {
        this.modifiedts = modifiedts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.OwnerPkString
     *
     * @return the value of medias.OwnerPkString
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getOwnerpkstring() {
        return ownerpkstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.OwnerPkString
     *
     * @param ownerpkstring the value for medias.OwnerPkString
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setOwnerpkstring(Long ownerpkstring) {
        this.ownerpkstring = ownerpkstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.aCLTS
     *
     * @return the value of medias.aCLTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getAclts() {
        return aclts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.aCLTS
     *
     * @param aclts the value for medias.aCLTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setAclts(Long aclts) {
        this.aclts = aclts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.propTS
     *
     * @return the value of medias.propTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getPropts() {
        return propts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.propTS
     *
     * @param propts the value for medias.propTS
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setPropts(Long propts) {
        this.propts = propts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.Mime
     *
     * @return the value of medias.Mime
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getMime() {
        return mime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.Mime
     *
     * @param mime the value for medias.Mime
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setMime(String mime) {
        this.mime = mime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.RealFileName
     *
     * @return the value of medias.RealFileName
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getRealfilename() {
        return realfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.RealFileName
     *
     * @param realfilename the value for medias.RealFileName
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setRealfilename(String realfilename) {
        this.realfilename = realfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_alttext
     *
     * @return the value of medias.p_alttext
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getpAlttext() {
        return pAlttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_alttext
     *
     * @param pAlttext the value for medias.p_alttext
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpAlttext(String pAlttext) {
        this.pAlttext = pAlttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_folder
     *
     * @return the value of medias.p_folder
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpFolder() {
        return pFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_folder
     *
     * @param pFolder the value for medias.p_folder
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpFolder(Long pFolder) {
        this.pFolder = pFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_removable
     *
     * @return the value of medias.p_removable
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Boolean getpRemovable() {
        return pRemovable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_removable
     *
     * @param pRemovable the value for medias.p_removable
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpRemovable(Boolean pRemovable) {
        this.pRemovable = pRemovable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_catalogversion
     *
     * @return the value of medias.p_catalogversion
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpCatalogversion() {
        return pCatalogversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_catalogversion
     *
     * @param pCatalogversion the value for medias.p_catalogversion
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpCatalogversion(Long pCatalogversion) {
        this.pCatalogversion = pCatalogversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_description
     *
     * @return the value of medias.p_description
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getpDescription() {
        return pDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_description
     *
     * @param pDescription the value for medias.p_description
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpDescription(String pDescription) {
        this.pDescription = pDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_catalog
     *
     * @return the value of medias.p_catalog
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpCatalog() {
        return pCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_catalog
     *
     * @param pCatalog the value for medias.p_catalog
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpCatalog(Long pCatalog) {
        this.pCatalog = pCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_datapk
     *
     * @return the value of medias.p_datapk
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpDatapk() {
        return pDatapk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_datapk
     *
     * @param pDatapk the value for medias.p_datapk
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpDatapk(Long pDatapk) {
        this.pDatapk = pDatapk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_mediaformat
     *
     * @return the value of medias.p_mediaformat
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpMediaformat() {
        return pMediaformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_mediaformat
     *
     * @param pMediaformat the value for medias.p_mediaformat
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpMediaformat(Long pMediaformat) {
        this.pMediaformat = pMediaformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_mediacontainer
     *
     * @return the value of medias.p_mediacontainer
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpMediacontainer() {
        return pMediacontainer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_mediacontainer
     *
     * @param pMediacontainer the value for medias.p_mediacontainer
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpMediacontainer(Long pMediacontainer) {
        this.pMediacontainer = pMediacontainer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.Code
     *
     * @return the value of medias.Code
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.Code
     *
     * @param code the value for medias.Code
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_size
     *
     * @return the value of medias.p_size
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpSize() {
        return pSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_size
     *
     * @param pSize the value for medias.p_size
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpSize(Long pSize) {
        this.pSize = pSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_outputmimetype
     *
     * @return the value of medias.p_outputmimetype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getpOutputmimetype() {
        return pOutputmimetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_outputmimetype
     *
     * @param pOutputmimetype the value for medias.p_outputmimetype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpOutputmimetype(String pOutputmimetype) {
        this.pOutputmimetype = pOutputmimetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_inputmimetype
     *
     * @return the value of medias.p_inputmimetype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getpInputmimetype() {
        return pInputmimetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_inputmimetype
     *
     * @param pInputmimetype the value for medias.p_inputmimetype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpInputmimetype(String pInputmimetype) {
        this.pInputmimetype = pInputmimetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_sourceitem
     *
     * @return the value of medias.p_sourceitem
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpSourceitem() {
        return pSourceitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_sourceitem
     *
     * @param pSourceitem the value for medias.p_sourceitem
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpSourceitem(Long pSourceitem) {
        this.pSourceitem = pSourceitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_itemtimestamp
     *
     * @return the value of medias.p_itemtimestamp
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Date getpItemtimestamp() {
        return pItemtimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_itemtimestamp
     *
     * @param pItemtimestamp the value for medias.p_itemtimestamp
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpItemtimestamp(Date pItemtimestamp) {
        this.pItemtimestamp = pItemtimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_format
     *
     * @return the value of medias.p_format
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpFormat() {
        return pFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_format
     *
     * @param pFormat the value for medias.p_format
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpFormat(Long pFormat) {
        this.pFormat = pFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_quotecharacter
     *
     * @return the value of medias.p_quotecharacter
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Short getpQuotecharacter() {
        return pQuotecharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_quotecharacter
     *
     * @param pQuotecharacter the value for medias.p_quotecharacter
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpQuotecharacter(Short pQuotecharacter) {
        this.pQuotecharacter = pQuotecharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_commentcharacter
     *
     * @return the value of medias.p_commentcharacter
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Short getpCommentcharacter() {
        return pCommentcharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_commentcharacter
     *
     * @param pCommentcharacter the value for medias.p_commentcharacter
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpCommentcharacter(Short pCommentcharacter) {
        this.pCommentcharacter = pCommentcharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_removeonsuccess
     *
     * @return the value of medias.p_removeonsuccess
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Boolean getpRemoveonsuccess() {
        return pRemoveonsuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_removeonsuccess
     *
     * @param pRemoveonsuccess the value for medias.p_removeonsuccess
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpRemoveonsuccess(Boolean pRemoveonsuccess) {
        this.pRemoveonsuccess = pRemoveonsuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_linestoskip
     *
     * @return the value of medias.p_linestoskip
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpLinestoskip() {
        return pLinestoskip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_linestoskip
     *
     * @param pLinestoskip the value for medias.p_linestoskip
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpLinestoskip(Integer pLinestoskip) {
        this.pLinestoskip = pLinestoskip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_encoding
     *
     * @return the value of medias.p_encoding
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpEncoding() {
        return pEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_encoding
     *
     * @param pEncoding the value for medias.p_encoding
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpEncoding(Long pEncoding) {
        this.pEncoding = pEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_zipentry
     *
     * @return the value of medias.p_zipentry
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getpZipentry() {
        return pZipentry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_zipentry
     *
     * @param pZipentry the value for medias.p_zipentry
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpZipentry(String pZipentry) {
        this.pZipentry = pZipentry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_fieldseparator
     *
     * @return the value of medias.p_fieldseparator
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Short getpFieldseparator() {
        return pFieldseparator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_fieldseparator
     *
     * @param pFieldseparator the value for medias.p_fieldseparator
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpFieldseparator(Short pFieldseparator) {
        this.pFieldseparator = pFieldseparator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_cronjob
     *
     * @return the value of medias.p_cronjob
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpCronjob() {
        return pCronjob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_cronjob
     *
     * @param pCronjob the value for medias.p_cronjob
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpCronjob(Long pCronjob) {
        this.pCronjob = pCronjob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_cronjobpos
     *
     * @return the value of medias.p_cronjobpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpCronjobpos() {
        return pCronjobpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_cronjobpos
     *
     * @param pCronjobpos the value for medias.p_cronjobpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpCronjobpos(Integer pCronjobpos) {
        this.pCronjobpos = pCronjobpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_scheduledcount
     *
     * @return the value of medias.p_scheduledcount
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpScheduledcount() {
        return pScheduledcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_scheduledcount
     *
     * @param pScheduledcount the value for medias.p_scheduledcount
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpScheduledcount(Integer pScheduledcount) {
        this.pScheduledcount = pScheduledcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_allowscriptevaluation
     *
     * @return the value of medias.p_allowscriptevaluation
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Boolean getpAllowscriptevaluation() {
        return pAllowscriptevaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_allowscriptevaluation
     *
     * @param pAllowscriptevaluation the value for medias.p_allowscriptevaluation
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpAllowscriptevaluation(Boolean pAllowscriptevaluation) {
        this.pAllowscriptevaluation = pAllowscriptevaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_icon
     *
     * @return the value of medias.p_icon
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpIcon() {
        return pIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_icon
     *
     * @param pIcon the value for medias.p_icon
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpIcon(Long pIcon) {
        this.pIcon = pIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_compiledreport
     *
     * @return the value of medias.p_compiledreport
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpCompiledreport() {
        return pCompiledreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_compiledreport
     *
     * @param pCompiledreport the value for medias.p_compiledreport
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpCompiledreport(Long pCompiledreport) {
        this.pCompiledreport = pCompiledreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_publicationpreviewpos
     *
     * @return the value of medias.p_publicationpreviewpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpPublicationpreviewpos() {
        return pPublicationpreviewpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_publicationpreviewpos
     *
     * @param pPublicationpreviewpos the value for medias.p_publicationpreviewpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpPublicationpreviewpos(Integer pPublicationpreviewpos) {
        this.pPublicationpreviewpos = pPublicationpreviewpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_configuration
     *
     * @return the value of medias.p_configuration
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpConfiguration() {
        return pConfiguration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_configuration
     *
     * @param pConfiguration the value for medias.p_configuration
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpConfiguration(Long pConfiguration) {
        this.pConfiguration = pConfiguration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_pagepreview
     *
     * @return the value of medias.p_pagepreview
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpPagepreview() {
        return pPagepreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_pagepreview
     *
     * @param pPagepreview the value for medias.p_pagepreview
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpPagepreview(Long pPagepreview) {
        this.pPagepreview = pPagepreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_publicationpreview
     *
     * @return the value of medias.p_publicationpreview
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpPublicationpreview() {
        return pPublicationpreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_publicationpreview
     *
     * @param pPublicationpreview the value for medias.p_publicationpreview
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpPublicationpreview(Long pPublicationpreview) {
        this.pPublicationpreview = pPublicationpreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_chapterpreview
     *
     * @return the value of medias.p_chapterpreview
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpChapterpreview() {
        return pChapterpreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_chapterpreview
     *
     * @param pChapterpreview the value for medias.p_chapterpreview
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpChapterpreview(Long pChapterpreview) {
        this.pChapterpreview = pChapterpreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_chapterpreviewpos
     *
     * @return the value of medias.p_chapterpreviewpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpChapterpreviewpos() {
        return pChapterpreviewpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_chapterpreviewpos
     *
     * @param pChapterpreviewpos the value for medias.p_chapterpreviewpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpChapterpreviewpos(Integer pChapterpreviewpos) {
        this.pChapterpreviewpos = pChapterpreviewpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_pagepreviewpos
     *
     * @return the value of medias.p_pagepreviewpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpPagepreviewpos() {
        return pPagepreviewpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_pagepreviewpos
     *
     * @param pPagepreviewpos the value for medias.p_pagepreviewpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpPagepreviewpos(Integer pPagepreviewpos) {
        this.pPagepreviewpos = pPagepreviewpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_celumid
     *
     * @return the value of medias.p_celumid
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpCelumid() {
        return pCelumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_celumid
     *
     * @param pCelumid the value for medias.p_celumid
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpCelumid(Integer pCelumid) {
        this.pCelumid = pCelumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_binarychangedcounter
     *
     * @return the value of medias.p_binarychangedcounter
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpBinarychangedcounter() {
        return pBinarychangedcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_binarychangedcounter
     *
     * @param pBinarychangedcounter the value for medias.p_binarychangedcounter
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpBinarychangedcounter(Integer pBinarychangedcounter) {
        this.pBinarychangedcounter = pBinarychangedcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_rawassetpos
     *
     * @return the value of medias.p_rawassetpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpRawassetpos() {
        return pRawassetpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_rawassetpos
     *
     * @param pRawassetpos the value for medias.p_rawassetpos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpRawassetpos(Integer pRawassetpos) {
        this.pRawassetpos = pRawassetpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_parameters
     *
     * @return the value of medias.p_parameters
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getpParameters() {
        return pParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_parameters
     *
     * @param pParameters the value for medias.p_parameters
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpParameters(String pParameters) {
        this.pParameters = pParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_deleted
     *
     * @return the value of medias.p_deleted
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Boolean getpDeleted() {
        return pDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_deleted
     *
     * @param pDeleted the value for medias.p_deleted
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpDeleted(Boolean pDeleted) {
        this.pDeleted = pDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_synchronized
     *
     * @return the value of medias.p_synchronized
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Boolean getpSynchronized() {
        return pSynchronized;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_synchronized
     *
     * @param pSynchronized the value for medias.p_synchronized
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpSynchronized(Boolean pSynchronized) {
        this.pSynchronized = pSynchronized;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_assettype
     *
     * @return the value of medias.p_assettype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpAssettype() {
        return pAssettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_assettype
     *
     * @param pAssettype the value for medias.p_assettype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpAssettype(Long pAssettype) {
        this.pAssettype = pAssettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_rawasset
     *
     * @return the value of medias.p_rawasset
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpRawasset() {
        return pRawasset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_rawasset
     *
     * @param pRawasset the value for medias.p_rawasset
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpRawasset(Long pRawasset) {
        this.pRawasset = pRawasset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_fileextension
     *
     * @return the value of medias.p_fileextension
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getpFileextension() {
        return pFileextension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_fileextension
     *
     * @param pFileextension the value for medias.p_fileextension
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpFileextension(String pFileextension) {
        this.pFileextension = pFileextension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_locationhash
     *
     * @return the value of medias.p_locationhash
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getpLocationhash() {
        return pLocationhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_locationhash
     *
     * @param pLocationhash the value for medias.p_locationhash
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpLocationhash(String pLocationhash) {
        this.pLocationhash = pLocationhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_subfolderpath
     *
     * @return the value of medias.p_subfolderpath
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getpSubfolderpath() {
        return pSubfolderpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_subfolderpath
     *
     * @param pSubfolderpath the value for medias.p_subfolderpath
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpSubfolderpath(String pSubfolderpath) {
        this.pSubfolderpath = pSubfolderpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_pagepos
     *
     * @return the value of medias.p_pagepos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpPagepos() {
        return pPagepos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_pagepos
     *
     * @param pPagepos the value for medias.p_pagepos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpPagepos(Integer pPagepos) {
        this.pPagepos = pPagepos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_page
     *
     * @return the value of medias.p_page
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpPage() {
        return pPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_page
     *
     * @param pPage the value for medias.p_page
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpPage(Long pPage) {
        this.pPage = pPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_product1nto
     *
     * @return the value of medias.p_product1nto
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpProduct1nto() {
        return pProduct1nto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_product1nto
     *
     * @param pProduct1nto the value for medias.p_product1nto
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpProduct1nto(Long pProduct1nto) {
        this.pProduct1nto = pProduct1nto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_product1nfrom
     *
     * @return the value of medias.p_product1nfrom
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpProduct1nfrom() {
        return pProduct1nfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_product1nfrom
     *
     * @param pProduct1nfrom the value for medias.p_product1nfrom
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpProduct1nfrom(Long pProduct1nfrom) {
        this.pProduct1nfrom = pProduct1nfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_product1nfrompos
     *
     * @return the value of medias.p_product1nfrompos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Integer getpProduct1nfrompos() {
        return pProduct1nfrompos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_product1nfrompos
     *
     * @param pProduct1nfrompos the value for medias.p_product1nfrompos
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpProduct1nfrompos(Integer pProduct1nfrompos) {
        this.pProduct1nfrompos = pProduct1nfrompos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_contextitem
     *
     * @return the value of medias.p_contextitem
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpContextitem() {
        return pContextitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_contextitem
     *
     * @param pContextitem the value for medias.p_contextitem
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpContextitem(Long pContextitem) {
        this.pContextitem = pContextitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_deeplinkurl
     *
     * @return the value of medias.p_deeplinkurl
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpDeeplinkurl() {
        return pDeeplinkurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_deeplinkurl
     *
     * @param pDeeplinkurl the value for medias.p_deeplinkurl
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpDeeplinkurl(Long pDeeplinkurl) {
        this.pDeeplinkurl = pDeeplinkurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_barcodetype
     *
     * @return the value of medias.p_barcodetype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public Long getpBarcodetype() {
        return pBarcodetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_barcodetype
     *
     * @param pBarcodetype the value for medias.p_barcodetype
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpBarcodetype(Long pBarcodetype) {
        this.pBarcodetype = pBarcodetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medias.p_barcodetext
     *
     * @return the value of medias.p_barcodetext
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public String getpBarcodetext() {
        return pBarcodetext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medias.p_barcodetext
     *
     * @param pBarcodetext the value for medias.p_barcodetext
     *
     * @mbg.generated Thu Oct 26 10:16:21 AEDT 2017
     */
    public void setpBarcodetext(String pBarcodetext) {
        this.pBarcodetext = pBarcodetext;
    }
}