package au.com.jaycar.mdm.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Productfeatures {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.PK
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Long pk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.hjmpTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Long hjmpts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.TypePkString
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Long typepkstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.createdTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Date createdts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.modifiedTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Date modifiedts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.OwnerPkString
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Long ownerpkstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.aCLTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Long aclts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.propTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Long propts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_description
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private String pDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_language
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Long pLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_unit
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Long pUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_valuedetails
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private String pValuedetails;


    private String pStringvalue;

  public String getpStringvalue() {
    return pStringvalue;
  }

  public void setpStringvalue(String pStringvalue) {
    this.pStringvalue = pStringvalue;
  }

  /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_valuetype
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Integer pValuetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_valueposition
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Integer pValueposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_booleanvalue
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Boolean pBooleanvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_qualifier
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private String pQualifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_numbervalue
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private BigDecimal pNumbervalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_classificationattributeassig
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Long pClassificationattributeassig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_product
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Long pProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productfeatures.p_featureposition
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    private Integer pFeatureposition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.PK
     *
     * @return the value of productfeatures.PK
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Long getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.PK
     *
     * @param pk the value for productfeatures.PK
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setPk(Long pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.hjmpTS
     *
     * @return the value of productfeatures.hjmpTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Long getHjmpts() {
        return hjmpts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.hjmpTS
     *
     * @param hjmpts the value for productfeatures.hjmpTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setHjmpts(Long hjmpts) {
        this.hjmpts = hjmpts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.TypePkString
     *
     * @return the value of productfeatures.TypePkString
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Long getTypepkstring() {
        return typepkstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.TypePkString
     *
     * @param typepkstring the value for productfeatures.TypePkString
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setTypepkstring(Long typepkstring) {
        this.typepkstring = typepkstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.createdTS
     *
     * @return the value of productfeatures.createdTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Date getCreatedts() {
        return createdts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.createdTS
     *
     * @param createdts the value for productfeatures.createdTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setCreatedts(Date createdts) {
        this.createdts = createdts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.modifiedTS
     *
     * @return the value of productfeatures.modifiedTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Date getModifiedts() {
        return modifiedts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.modifiedTS
     *
     * @param modifiedts the value for productfeatures.modifiedTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setModifiedts(Date modifiedts) {
        this.modifiedts = modifiedts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.OwnerPkString
     *
     * @return the value of productfeatures.OwnerPkString
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Long getOwnerpkstring() {
        return ownerpkstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.OwnerPkString
     *
     * @param ownerpkstring the value for productfeatures.OwnerPkString
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setOwnerpkstring(Long ownerpkstring) {
        this.ownerpkstring = ownerpkstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.aCLTS
     *
     * @return the value of productfeatures.aCLTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Long getAclts() {
        return aclts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.aCLTS
     *
     * @param aclts the value for productfeatures.aCLTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setAclts(Long aclts) {
        this.aclts = aclts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.propTS
     *
     * @return the value of productfeatures.propTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Long getPropts() {
        return propts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.propTS
     *
     * @param propts the value for productfeatures.propTS
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setPropts(Long propts) {
        this.propts = propts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_description
     *
     * @return the value of productfeatures.p_description
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public String getpDescription() {
        return pDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_description
     *
     * @param pDescription the value for productfeatures.p_description
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpDescription(String pDescription) {
        this.pDescription = pDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_language
     *
     * @return the value of productfeatures.p_language
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Long getpLanguage() {
        return pLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_language
     *
     * @param pLanguage the value for productfeatures.p_language
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpLanguage(Long pLanguage) {
        this.pLanguage = pLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_unit
     *
     * @return the value of productfeatures.p_unit
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Long getpUnit() {
        return pUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_unit
     *
     * @param pUnit the value for productfeatures.p_unit
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpUnit(Long pUnit) {
        this.pUnit = pUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_valuedetails
     *
     * @return the value of productfeatures.p_valuedetails
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public String getpValuedetails() {
        return pValuedetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_valuedetails
     *
     * @param pValuedetails the value for productfeatures.p_valuedetails
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpValuedetails(String pValuedetails) {
        this.pValuedetails = pValuedetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_valuetype
     *
     * @return the value of productfeatures.p_valuetype
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Integer getpValuetype() {
        return pValuetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_valuetype
     *
     * @param pValuetype the value for productfeatures.p_valuetype
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpValuetype(Integer pValuetype) {
        this.pValuetype = pValuetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_valueposition
     *
     * @return the value of productfeatures.p_valueposition
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Integer getpValueposition() {
        return pValueposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_valueposition
     *
     * @param pValueposition the value for productfeatures.p_valueposition
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpValueposition(Integer pValueposition) {
        this.pValueposition = pValueposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_booleanvalue
     *
     * @return the value of productfeatures.p_booleanvalue
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Boolean getpBooleanvalue() {
        return pBooleanvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_booleanvalue
     *
     * @param pBooleanvalue the value for productfeatures.p_booleanvalue
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpBooleanvalue(Boolean pBooleanvalue) {
        this.pBooleanvalue = pBooleanvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_qualifier
     *
     * @return the value of productfeatures.p_qualifier
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public String getpQualifier() {
        return pQualifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_qualifier
     *
     * @param pQualifier the value for productfeatures.p_qualifier
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpQualifier(String pQualifier) {
        this.pQualifier = pQualifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_numbervalue
     *
     * @return the value of productfeatures.p_numbervalue
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public BigDecimal getpNumbervalue() {
        return pNumbervalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_numbervalue
     *
     * @param pNumbervalue the value for productfeatures.p_numbervalue
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpNumbervalue(BigDecimal pNumbervalue) {
        this.pNumbervalue = pNumbervalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_classificationattributeassig
     *
     * @return the value of productfeatures.p_classificationattributeassig
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Long getpClassificationattributeassig() {
        return pClassificationattributeassig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_classificationattributeassig
     *
     * @param pClassificationattributeassig the value for productfeatures.p_classificationattributeassig
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpClassificationattributeassig(Long pClassificationattributeassig) {
        this.pClassificationattributeassig = pClassificationattributeassig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_product
     *
     * @return the value of productfeatures.p_product
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Long getpProduct() {
        return pProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_product
     *
     * @param pProduct the value for productfeatures.p_product
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpProduct(Long pProduct) {
        this.pProduct = pProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productfeatures.p_featureposition
     *
     * @return the value of productfeatures.p_featureposition
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public Integer getpFeatureposition() {
        return pFeatureposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productfeatures.p_featureposition
     *
     * @param pFeatureposition the value for productfeatures.p_featureposition
     *
     * @mbg.generated Tue Oct 17 16:20:33 AEDT 2017
     */
    public void setpFeatureposition(Integer pFeatureposition) {
        this.pFeatureposition = pFeatureposition;
    }
}
