/*
 * Created on 29 Sep 2017 ( Time 15:10:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package au.com.jaycar.local.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import au.com.jaycar.local.entity.Products;
import au.com.jaycar.local.entity.jpa.ProductsEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ProductsServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ProductsServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ProductsEntity' to 'Products'
	 * @param productsEntity
	 */
	public Products mapProductsEntityToProducts(ProductsEntity productsEntity) {
		if(productsEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Products products = map(productsEntity, Products.class);

		return products;
	}
	
	/**
	 * Mapping from 'Products' to 'ProductsEntity'
	 * @param products
	 * @param productsEntity
	 */
	public void mapProductsToProductsEntity(Products products, ProductsEntity productsEntity) {
		if(products == null) {
			return;
		}

		//--- Generic mapping 
		map(products, productsEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}