/*
 * Created on 29 Sep 2017 ( Time 15:10:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package au.com.jaycar.local.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import au.com.jaycar.local.entity.Stock;
import au.com.jaycar.local.entity.jpa.StockEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class StockServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public StockServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'StockEntity' to 'Stock'
	 * @param stockEntity
	 */
	public Stock mapStockEntityToStock(StockEntity stockEntity) {
		if(stockEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Stock stock = map(stockEntity, Stock.class);

		return stock;
	}
	
	/**
	 * Mapping from 'Stock' to 'StockEntity'
	 * @param stock
	 * @param stockEntity
	 */
	public void mapStockToStockEntity(Stock stock, StockEntity stockEntity) {
		if(stock == null) {
			return;
		}

		//--- Generic mapping 
		map(stock, stockEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}