/*
 * Created on 3 Oct 2017 ( Time 11:55:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package au.com.jaycar.local.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "stock"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="stock", catalog="coreinfo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Stock.countAll", query="SELECT COUNT(x) FROM Stock x" )
} )
public class Stock implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="PK", nullable=false)
    private Integer    pk           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="code", length=10)
    private String     code         ;

    @Column(name="stk_loc", length=45)
    private String     stkLoc       ;

    @Column(name="stk_stkqty")
    private Integer    stkStkqty    ;

    @Column(name="stk_allstk")
    private Integer    stkAllstk    ;

    @Column(name="stocklevel")
    private Integer    stocklevel   ;

    @Column(name="stk_totord")
    private Integer    stkTotord    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Stock()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPk( Integer pk )
    {
        this.pk = pk ;
    }
    public Integer getPk()
    {
        return this.pk;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : code ( VARCHAR ) 
    public void setCode( String code )
    {
        this.code = code;
    }
    public String getCode()
    {
        return this.code;
    }

    //--- DATABASE MAPPING : stk_loc ( VARCHAR ) 
    public void setStkLoc( String stkLoc )
    {
        this.stkLoc = stkLoc;
    }
    public String getStkLoc()
    {
        return this.stkLoc;
    }

    //--- DATABASE MAPPING : stk_stkqty ( INT ) 
    public void setStkStkqty( Integer stkStkqty )
    {
        this.stkStkqty = stkStkqty;
    }
    public Integer getStkStkqty()
    {
        return this.stkStkqty;
    }

    //--- DATABASE MAPPING : stk_allstk ( INT ) 
    public void setStkAllstk( Integer stkAllstk )
    {
        this.stkAllstk = stkAllstk;
    }
    public Integer getStkAllstk()
    {
        return this.stkAllstk;
    }

    //--- DATABASE MAPPING : stocklevel ( INT ) 
    public void setStocklevel( Integer stocklevel )
    {
        this.stocklevel = stocklevel;
    }
    public Integer getStocklevel()
    {
        return this.stocklevel;
    }

    //--- DATABASE MAPPING : stk_totord ( INT ) 
    public void setStkTotord( Integer stkTotord )
    {
        this.stkTotord = stkTotord;
    }
    public Integer getStkTotord()
    {
        return this.stkTotord;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(pk);
        sb.append("]:"); 
        sb.append(code);
        sb.append("|");
        sb.append(stkLoc);
        sb.append("|");
        sb.append(stkStkqty);
        sb.append("|");
        sb.append(stkAllstk);
        sb.append("|");
        sb.append(stocklevel);
        sb.append("|");
        sb.append(stkTotord);
        return sb.toString(); 
    } 

}