/*
 * Created on 29 Sep 2017 ( Time 15:10:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package au.com.jaycar.local.business.service;

import java.util.List;

import au.com.jaycar.local.entity.Polines;
import au.com.jaycar.local.entity.Products;

/**
 * Business Service Interface for entity Polines.
 */
public interface PolinesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param pk
	 * @return entity
	 */
	Polines findById( Integer pk  ) ;

	
	/**
	 * Loads an entity from the database using its Primary Key
	 * @param pk
	 * @return entity
	 */
	Polines findByCode( String code  ) ;
	
	
	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Polines> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Polines save(Polines entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Polines update(Polines entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Polines create(Polines entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param pk
	 */
	void delete( Integer pk );


}
