/*
 * Created on 29 Sep 2017 ( Time 15:10:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package au.com.jaycar.local.business.service;

import java.util.List;

import au.com.jaycar.local.entity.Products;

/**
 * Business Service Interface for entity Products.
 */
public interface ProductsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param pk
	 * @return entity
	 */
	Products findById( Integer pk  ) ;
	
	
	/**
	 * Loads an entity from the database using its Primary Key
	 * @param pk
	 * @return entity
	 */
	Products findByCode( String code  ) ;
	
	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Products> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Products save(Products entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Products update(Products entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Products create(Products entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param pk
	 */
	void delete( Integer pk );

}
