/*
 * Created on 29 Sep 2017 ( Time 15:10:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package au.com.jaycar.local.business.service;

import java.util.List;

import au.com.jaycar.local.entity.Products;
import au.com.jaycar.local.entity.Relatedproducts;

/**
 * Business Service Interface for entity Relatedproducts.
 */
public interface RelatedproductsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param pk
	 * @return entity
	 */
	Relatedproducts findById( Integer pk  ) ;
	
	
	/**
	 * Loads an entity from the database using its Primary Key
	 * @param pk
	 * @return entity
	 */
	Relatedproducts findByCode( String code  ) ;
	

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Relatedproducts> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Relatedproducts save(Relatedproducts entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Relatedproducts update(Relatedproducts entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Relatedproducts create(Relatedproducts entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param pk
	 */
	void delete( Integer pk );


}
