/*
 * Created on 29 Sep 2017 ( Time 15:10:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package au.com.jaycar.mdm.service.impl;


import java.util.Map;

import javax.annotation.Resource;

import java.util.HashMap;
import java.util.List;

import au.com.jaycar.mdm.dao.ProductsDao;
import au.com.jaycar.mdm.entity.Products;
import au.com.jaycar.mdm.entity.ProductsWithBLOBs;
import au.com.jaycar.mdm.service.MdmProductsService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Implementation of ProductsService
 */
@Component
public class MdmProductsServiceImpl implements MdmProductsService {

	@Resource
	ProductsDao productsDao;


	@Override
	public ProductsWithBLOBs findByCode(String code) {
		
		Map<String, Object> queryParameters = new HashMap<String, Object>();
		queryParameters.put("code", code);
		
		ProductsWithBLOBs products = productsDao.findByCode(code);
		return products;
		
	}
	
	@Override
	public List<ProductsWithBLOBs> findAll() {
		
		List<ProductsWithBLOBs> products = productsDao.findAll();
		return products;
	
	}
}
