/*
 * Created on 29 Sep 2017 ( Time 15:10:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package au.com.jaycar.mdm.service.impl;


import java.util.Map;

import javax.annotation.Resource;

import java.util.HashMap;
import java.util.List;

import au.com.jaycar.mdm.dao.ProductsDao;
import au.com.jaycar.mdm.dao.RelatedProductsDao;
import au.com.jaycar.mdm.entity.Products;
import au.com.jaycar.mdm.entity.ProductsWithBLOBs;
import au.com.jaycar.mdm.entity.RelatedProducts;
import au.com.jaycar.mdm.service.MdmProductsService;
import au.com.jaycar.mdm.service.MdmRelatedProductsService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Implementation of ProductsService
 */
@Component
public class MdmRelatedProductsServiceImpl implements MdmRelatedProductsService {

	@Resource
	RelatedProductsDao relatedProductsDao;


	@Override
	public List<RelatedProducts> findByCode(String code) {
		
		Map<String, Object> queryParameters = new HashMap<String, Object>();
		queryParameters.put("code", code);
		
		List<RelatedProducts> products = relatedProductsDao.findByCode(code);
		return products;
		
	}
}
